using Microsoft.VisualStudio.TestTools.UnitTesting;
using SPIXI;
using System.Collections.Generic;
using System.Linq;

namespace Spixi_UnitTests
{
    /* ★★ #1106 — executes the C# port of the chat bubble's link rule (Spixi/Utils/LinkRule.cs). The expected lists are
     * what the SHELL's own rule (src/components/message-bubble.js URL_RE + linkifyPlain) returned for the same texts,
     * generated by running the shell code (session 1, cloud parity run: 26 texts, 0 differences). Run on the PC:
     *   dotnet test Spixi-UnitTests\Spixi-UnitTests.csproj --filter LinkRule */
    [TestClass]
    public class LinkRuleTests
    {
        private static readonly object[][] corpus = new object[][]
        {
            new object[] { "see https://example.com/path?q=1.", new string[] { "https://example.com/path?q=1" } },
            new object[] { "github.com and www.spixi.io!", new string[] { "github.com", "www.spixi.io" } },
            new object[] { "mail a@b.com now", new string[] {  } },
            new object[] { "path/x.com no", new string[] {  } },
            new object[] { "(see https://x.com/a)", new string[] { "https://x.com/a" } },
            new object[] { "https://x.com/(a)b)", new string[] { "https://x.com/(a)b" } },
            new object[] { "file.txt node.js v1.2.3", new string[] {  } },
            new object[] { "HTTP://UPPER.COM/X", new string[] { "HTTP://UPPER.COM/X" } },
            new object[] { "two: ixian.io, spixi.io;", new string[] { "ixian.io", "spixi.io" } },
            new object[] { "glued-x.com", new string[] { "glued-x.com" } },
            new object[] { "tenor https://media.tenor.com/abc.gif", new string[] { "https://media.tenor.com/abc.gif" } },
            new object[] { "word.co.uk/x?y=z", new string[] { "word.co.uk/x?y=z" } },
            new object[] { "nothing here", new string[] {  } },
            new object[] { "https://paypal.com@evil.com/login", new string[] { "https://paypal.com@evil.com/login" } },
            new object[] { "a.b.c.d.e.f.com", new string[] { "a.b.c.d.e.f.com" } },
            new object[] { "end with colon spixi.io:", new string[] { "spixi.io" } },
            new object[] { "日本 https://例え.jp/パス", new string[] { "https://例え.jp/パス" } },
            new object[] { "trailing ))) https://a.com/b)))", new string[] { "https://a.com/b" } },
            new object[] { "\"https://q.com\" 'www.r.org'", new string[] { "https://q.com", "www.r.org" } },
            new object[] { "under_score.com x_y.com", new string[] {  } },
            new object[] { "ÄÖ.com über.de", new string[] { "ber.de" } },
            new object[] { "https://a.com\u00a0b.com", new string[] { "https://a.com", "b.com" } },
            new object[] { "-dash.com", new string[] {  } },
            new object[] { ".dot.com", new string[] {  } },
            new object[] { "MiXeD.CoM/Path", new string[] { "MiXeD.CoM/Path" } },
        };

        [TestMethod]
        public void SameLinksAsTheChatBubble()
        {
            foreach (object[] row in corpus)
            {
                string text = (string)row[0];
                string[] want = (string[])row[1];
                List<string> got = LinkRule.extract(text);
                Assert.IsTrue(want.SequenceEqual(got), "text: " + text + " → got [" + string.Join(" | ", got) + "]");
            }
        }

        [TestMethod]
        public void ExactlyTheCapStillLinks()
        {
            string t = "a.com" + new string(' ', LinkRule.LinkifyMax - 5);
            Assert.AreEqual(LinkRule.LinkifyMax, t.Length);
            Assert.AreEqual(1, LinkRule.extract(t).Count, "(#46 r1 M21) the shell linkifies a text of exactly 4096 chars (its test is > 4096)");
        }

        [TestMethod]
        public void OverTheCapListsNothing()
        {
            Assert.AreEqual(0, LinkRule.extract("a.com" + new string(' ', LinkRule.LinkifyMax)).Count, "the shell does not linkify text over 4096 chars");
        }
    }
}
