/* GENERATED by scripts/build-demo-bundle.mjs — DO NOT EDIT.
 * Real component sources bundled for file:// demos. Requires icons.iife.js first.
 */
(function () {
  var icon = window.SpixiIcons.icon;
  var ICONS = window.SpixiIcons.ICONS;

/* ---- src/components/timestamp.js ---- */
/**
 * Chat-list timestamp formatting (docs/chat-list-spec.md §3).
 * today → HH:mm (12/24h follows device locale) · yesterday → localized
 * "Yesterday" · 2–6 days → weekday · same year → DD MMM · older → DD MMM YYYY.
 * Locale from document/browser; localized strings arrive via window.SL
 * (i18n plan, ARCHITECTURE.md §7).
 */
function dayBucketLabel(ts, strings = {}, now = Date.now(), todayLabel = null) {
  const d = new Date(ts);
  const n = new Date(now);
  const locale = document.documentElement.lang || undefined;
  const startOfDay = (x) => new Date(x.getFullYear(), x.getMonth(), x.getDate()).getTime();
  const dayDiff = Math.round((startOfDay(n) - startOfDay(d)) / 86400000);
  if (dayDiff <= 0) return todayLabel;
  if (dayDiff === 1) return strings.yesterday || 'Yesterday';
  if (dayDiff < 7) return d.toLocaleDateString(locale, { weekday: 'long' });
  if (d.getFullYear() === n.getFullYear()) {
    return d.toLocaleDateString(locale, { day: '2-digit', month: 'short' });
  }
  return d.toLocaleDateString(locale, { day: '2-digit', month: 'short', year: 'numeric' });
}
function formatChatTimestamp(ts, strings = {}, now = Date.now()) {
  const bucket = dayBucketLabel(ts, strings, now, null);
  if (bucket !== null) return bucket;
  const locale = document.documentElement.lang || undefined;
  return new Date(ts).toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' });
}

/**
 * Absolute timestamp for transaction rows (docs/tx-row-spec.md): "20 Mar, 9:15".
 * Device locale for month + 12/24h; no ticker — absolute dates don't go stale.
 */
function formatTxTimestamp(ts, now = Date.now()) {
  const d = new Date(ts);
  const locale = document.documentElement.lang || undefined;
  const sameYear = d.getFullYear() === new Date(now).getFullYear();
  const date = d.toLocaleDateString(locale, sameYear
    ? { day: 'numeric', month: 'short' }
    : { day: 'numeric', month: 'short', year: 'numeric' });
  const time = d.toLocaleTimeString(locale, { hour: 'numeric', minute: '2-digit' });
  return date + ', ' + time;
}

let activeStop = null; // single shared ticker — starting a new one stops the previous

/**
 * One shared scheduler (not per-row timers): fires `cb` every minute while the
 * page is visible (today-times may change), at midnight rollover
 * (re-classification of every row), and immediately when the document becomes
 * visible again (timers are skipped/suspended while hidden). Ticks are aligned
 * to the minute boundary. Returns a stop function.
 */
function startTimestampTicker(cb) {
  if (activeStop) activeStop();

  let minuteTimeout, minuteInterval, midnightTimer;
  const tick = () => { if (!document.hidden) cb(); };

  // align to the next minute boundary, then every 60s
  minuteTimeout = setTimeout(() => {
    tick();
    minuteInterval = setInterval(tick, 60000);
  }, 60000 - (Date.now() % 60000));

  const scheduleMidnight = () => {
    const now = new Date();
    const next = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 0, 0, 1);
    return setTimeout(() => { cb(); midnightTimer = scheduleMidnight(); }, next - now);
  };
  midnightTimer = scheduleMidnight();

  const onVisibility = () => { if (!document.hidden) cb(); };
  document.addEventListener('visibilitychange', onVisibility);

  const stop = () => {
    clearTimeout(minuteTimeout);
    clearInterval(minuteInterval);
    clearTimeout(midnightTimer);
    document.removeEventListener('visibilitychange', onVisibility);
    if (activeStop === stop) activeStop = null;
  };
  activeStop = stop;
  return stop;
}

/* ---- src/components/avatar.js ---- */
/**
 * c-avatar — photo, or deterministic gradient placeholder (DECISIONS.md #34).
 * Hue derives from the address hash → stable identity color per contact.
 * Named contacts show initials; address-only contacts show the user glyph.
 *
 * createAvatar({ src, name, address, size = 48, online = false })
 */


function hashHue(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  // avalanche mix (murmur3 finalizer) — plain h%360 clustered similar Latin
  // names into a ~30° hue band (all-olive avatars); this scatters them (#38)
  h ^= h >>> 16;
  h = Math.imul(h, 0x45d9f3b);
  h = (h ^ (h >>> 16)) >>> 0;
  return h % 360;
}

function initials(name) {
  const trimmed = name.trim();
  // must start with a letter (any script) — empty/whitespace-only and
  // address-like hex "names" get the glyph instead of initials
  if (!/^\p{L}/u.test(trimmed)) return null;
  // [...p] not p[0]: first char may be an astral-plane code point (CJK ext.)
  return trimmed.split(/\s+/).slice(0, 2).map(p => [...p][0].toLocaleUpperCase()).join('');
}

function createAvatar({ src = null, name = '', address = '', size = 48, online = false } = {}) {
  const el = document.createElement('span');
  el.className = 'c-avatar';
  el.dataset.size = String(size);
  if (size !== 24 && size !== 48) {
    // known sizes (24/48) come from --size-avatar-* tokens in avatar.css;
    // anything else falls back to inline sizing until tokenized
    el.style.width = size + 'px';
    el.style.height = size + 'px';
  }

  if (src) {
    const img = document.createElement('img');
    img.className = 'c-avatar__img';
    img.src = src;
    img.alt = '';
    el.append(img);
  } else {
    const hue = hashHue(address || name);
    // JS supplies ONLY the deterministic hues; saturation/lightness are themed
    // in avatar.css (--avatar-grad-*) so gradients adapt to light/dark (#37)
    el.dataset.placeholder = '';
    el.style.setProperty('--av-h1', hue);
    el.style.setProperty('--av-h2', (hue + 40) % 360);
    const ini = name ? initials(name) : null;
    if (ini) {
      const t = document.createElement('span');
      t.className = 'c-avatar__initials';
      t.setAttribute('aria-hidden', 'true'); // audit r2: SRs read "HS Han Solo"
      t.textContent = ini;
      el.append(t);
    } else {
      el.append(icon('user-circle', { size: Math.round(size * 0.55) }));
    }
  }

  if (online) {
    const dot = document.createElement('span');
    dot.className = 'c-avatar__dot';
    el.append(dot);
  }
  return el;
}

/* ---- src/components/chatlist-item.js ---- */
/**
 * Chat list row family (docs/chat-list-spec.md): c-indicator, c-status-icon,
 * c-excerpt, c-chatlist-item. Bridge contract: addChat(...) — ARCHITECTURE.md §4.
 * All factories accept an optional `strings` dict (per-shell window.SL,
 * ARCHITECTURE.md §7); English defaults inline.
 */




/** Cap counts for compact badges/indicators (shared with c-bottomnav). */
function formatCount(n) {
  return n > 99 ? '99+' : String(n);
}

/* —— status icon (§2): sending/sent/delivered neutral · read accent · failed error —— */
const STATUS = {
  sending: { glyph: 'clock-hour-10', tone: 'neutral' },
  sent: { glyph: 'check', tone: 'neutral' },
  delivered: { glyph: 'checks', tone: 'neutral' },
  read: { glyph: 'checks', tone: 'read' },
  failed: { glyph: 'alert-small', tone: 'failed' },
};
function createStatusIcon(status) {
  const s = STATUS[status];
  if (!s) return null;
  const el = icon(s.glyph, { size: 16 });
  el.classList.add('c-status-icon');
  el.dataset.tone = s.tone;
  return el;
}

/* —— indicator (§4): count · count-muted · muted (bell-off) · mention (@ wins over count) —— */
function createIndicator({ count = 0, mention = false, muted = false, strings = {} } = {}) {
  const el = document.createElement('span');
  el.className = 'c-indicator';
  if (mention) {
    el.dataset.variant = 'mention';
    el.textContent = '@';
    el.setAttribute('aria-label', strings.mention || 'mention');
  } else if (count > 0) {
    el.dataset.variant = muted ? 'count-muted' : 'count';
    el.textContent = formatCount(count);
    el.setAttribute('aria-label', count + ' ' + (strings.unread || 'unread'));
  } else if (muted) {
    el.dataset.variant = 'muted';
    el.append(icon('bell-off', { size: 12 }));
    el.setAttribute('aria-label', strings.muted || 'muted');
  } else return null;
  return el;
}

/** Indicator set for row2: muted chats show BOTH the (muted) count/@ AND the
 *  bell-off glyph (Damir review 2026-07-02). Returns [] when nothing to show. */
function createIndicators({ count = 0, mention = false, muted = false, strings = {} } = {}) {
  const out = [];
  if (mention || count > 0) out.push(createIndicator({ count, mention, muted, strings }));
  if (muted) out.push(createIndicator({ muted: true, strings }));
  return out;
}

/* —— excerpt (§5): type → optional 16px glyph + toned text parts —— */
const EXCERPT_GLYPHS = {
  file: 'file-isr', gif: 'gif', call: 'phone', 'call-missed': 'phone-off',
  payment: 'wallet', 'app-invite': 'apps', draft: 'pencil',
};
function createExcerpt({ type = 'text', text = '', sender = null, strings = {} } = {}) {
  const el = document.createElement('span');
  el.className = 'c-excerpt';
  el.dataset.type = type;
  const glyph = EXCERPT_GLYPHS[type];
  if (glyph) el.append(icon(glyph, { size: 16 }));
  if (sender) {
    const s = document.createElement('span');
    s.className = 'c-excerpt__sender';
    s.textContent = sender + ': ';
    el.append(s);
  }
  const t = document.createElement('span');
  t.className = 'c-excerpt__text';
  if (type === 'draft') {
    const prefix = document.createElement('span');
    prefix.className = 'c-excerpt__draft';
    prefix.textContent = strings.draft || 'Draft: ';
    t.append(prefix);
    t.append(document.createTextNode(text));
  } else if (type === 'mention' && text.includes('@')) {
    // highlight the first @token
    const i = text.indexOf('@');
    const end = text.indexOf(' ', i);
    const stop = end === -1 ? text.length : end;
    t.append(document.createTextNode(text.slice(0, i)));
    const m = document.createElement('span');
    m.className = 'c-excerpt__mention';
    m.textContent = text.slice(i, stop);
    t.append(m, document.createTextNode(text.slice(stop)));
  } else {
    t.textContent = text;
  }
  el.append(t);
  return el;
}

/* —— chat list row (§1, §6) —— */
function createChatItem({
  name, address = '', avatar = null, online = false,
  timestamp, status = null, pinned = false,
  unread = 0, mention = false, muted = false,
  excerpt = { type: 'text', text: '' },
  selected = false, onClick, strings = {},
} = {}) {
  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-chatlist-item';
  if (unread > 0 || mention) el.dataset.unread = '';
  // 'true' = selected list row (vs 'page' on bottomnav — a nav destination)
  if (selected) el.setAttribute('aria-current', 'true');

  el.append(createAvatar({ src: avatar, name, address, size: 48, online }));

  const content = document.createElement('span');
  content.className = 'c-chatlist-item__content';
  const nameEl = document.createElement('span');
  nameEl.className = 'c-chatlist-item__name';
  nameEl.textContent = name || address;
  content.append(nameEl, createExcerpt({ ...excerpt, strings }));
  el.append(content);

  const right = document.createElement('span');
  right.className = 'c-chatlist-item__right';
  const row1 = document.createElement('span');
  row1.className = 'c-chatlist-item__meta';
  const statusEl = createStatusIcon(status);
  if (statusEl) row1.append(statusEl);
  if (pinned) row1.append(icon('pin', { size: 16 }));
  if (timestamp != null) {
    const time = document.createElement('span');
    time.className = 'c-chatlist-item__time u-tabular';
    time.textContent = formatChatTimestamp(timestamp, strings);
    time.dataset.ts = timestamp;
    row1.append(time);
  }
  right.append(row1);
  const inds = createIndicators({ count: unread, mention, muted, strings });
  if (inds.length) {
    const row2 = document.createElement('span');
    row2.className = 'c-chatlist-item__indicators';
    row2.append(...inds);
    right.append(row2);
  }
  el.append(right);

  if (onClick) el.addEventListener('click', onClick);
  return el;
}

/** Refresh all rendered timestamps (call from startTimestampTicker);
 *  pass the same `strings` the rows were built with. */
function refreshTimestamps(rootEl, strings = {}) {
  for (const t of rootEl.querySelectorAll('.c-chatlist-item__time[data-ts]')) {
    t.textContent = formatChatTimestamp(Number(t.dataset.ts), strings);
  }
}

/* ---- src/components/button.js ---- */
/**
 * c-button — mirrors Figma button/{32,44,56}/{default,destructive}.
 * Conventions: DECISIONS.md #16 · state layers #28 · success pattern #29 · icon API #30.
 *
 * createButton({
 *   label: string,                     // omit for icon-only (ariaLabel required)
 *   type: 'fill' | 'tonal' | 'outline' | 'text' = 'fill',
 *   size: 32 | 44 | 56 = 44,
 *   intent: 'default' | 'destructive' = 'default',
 *   width: 'hug' | 'full' = 'hug',
 *   icon: SVGElement | null,
 *   iconPosition: 'leading' | 'trailing' = 'leading',
 *   ariaLabel: string,                 // required when no label (icon-only)
 *   loading: boolean = false,
 *   disabled: boolean = false,
 *   onClick: (event) => void
 * })
 */
function createButton({
  label,
  type = 'fill',
  size = 44,
  intent = 'default',
  width = 'hug',
  icon = null,
  iconPosition = 'leading',
  ariaLabel,
  loading = false,
  disabled = false,
  onClick,
} = {}) {
  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-button';
  el.dataset.type = type;
  el.dataset.size = String(size);
  el.dataset.intent = intent;
  el.dataset.width = width;

  const hasLabel = label != null && label !== '';
  if (!hasLabel) {
    el.dataset.iconOnly = '';
    if (ariaLabel) el.setAttribute('aria-label', ariaLabel);
    // no label + no ariaLabel is an accessibility bug — make it loud in dev
    else console.warn('c-button: icon-only button requires ariaLabel');
  }

  if (icon) icon.classList.add('c-button__icon');
  if (icon && iconPosition === 'leading') el.append(icon);

  if (hasLabel) {
    const text = document.createElement('span');
    text.className = 'c-button__label';
    text.textContent = label;
    el.append(text);
  }

  if (icon && iconPosition === 'trailing') el.append(icon);

  if (onClick) el.addEventListener('click', onClick);

  setLoading(el, loading);
  el.disabled = disabled;
  return el;
}

/**
 * Run a content mutation with an animated width morph (hug buttons only).
 * Measures old/new natural widths synchronously (no flicker), transitions
 * between them (CSS only transitions width while [data-morphing] is set),
 * then releases back to hug on transitionend (timeout fallback covers
 * reduced-motion / zero-duration, where transitionend never fires).
 */
const pendingMorph = new WeakMap(); // el → cancel fn for an in-flight release

function morphWidth(el, mutate) {
  if (el.dataset.width === 'full' || !el.isConnected) { mutate(); return; }
  const cancelPrev = pendingMorph.get(el);
  if (cancelPrev) cancelPrev(); // re-morph mid-flight: keep current width, retarget
  const w0 = el.offsetWidth;
  mutate();
  el.style.width = 'auto';
  const w1 = el.offsetWidth;
  el.style.width = w0 + 'px';
  el.dataset.morphing = '';
  void el.offsetWidth; // reflow so the transition has a start value
  el.style.width = w1 + 'px';

  let fallback;
  const cancel = () => {
    clearTimeout(fallback);
    el.removeEventListener('transitionend', onEnd);
    pendingMorph.delete(el);
  };
  const release = () => {
    cancel();
    el.style.width = '';
    delete el.dataset.morphing;
  };
  const onEnd = (e) => {
    if (e.target === el && e.propertyName === 'width') release();
  };
  el.addEventListener('transitionend', onEnd);
  // fallback must exceed --duration-200 (also covers reduced-motion 0ms, where
  // transitionend never fires); bump if the width-morph token is ever raised
  fallback = setTimeout(release, 400);
  pendingMorph.set(el, cancel);
}

/** Toggle loading state (spinner + aria-busy). Works for any type/intent. */
function setLoading(el, loading) {
  morphWidth(el, () => {
    const existing = el.querySelector('.c-button__spinner');
    if (loading) {
      if (!existing) {
        const spinner = document.createElement('span');
        spinner.className = 'c-button__spinner';
        spinner.setAttribute('aria-hidden', 'true');
        el.prepend(spinner);
      }
      el.dataset.loading = '';
      el.setAttribute('aria-busy', 'true');
    } else {
      existing?.remove();
      delete el.dataset.loading;
      el.removeAttribute('aria-busy');
    }
  });
}

const CHECK_PATH = 'M5 12l5 5L20 7'; // tabler check

/**
 * Transient success morph (DECISIONS.md #29): loading off → solid success surface
 * + check + optional label swap, announced politely, restored after `duration`.
 * Use ONLY for in-place actions with no other confirmation (no toast, no navigation).
 */
function setSuccess(el, { label = null, duration = 1400 } = {}) {
  if (el.dataset.success !== undefined) return;

  const original = [...el.childNodes].filter(n => !n.classList?.contains('c-button__spinner'));
  const originalDisabled = el.disabled;

  morphWidth(el, () => {
    el.textContent = '';
    el.dataset.success = '';
    el.disabled = true;
    delete el.dataset.loading;
    el.removeAttribute('aria-busy');

    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttribute('viewBox', '0 0 24 24');
    svg.setAttribute('fill', 'none');
    svg.setAttribute('aria-hidden', 'true');
    svg.classList.add('c-button__icon');
    const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    path.setAttribute('d', CHECK_PATH);
    path.setAttribute('stroke', 'currentColor');
    path.setAttribute('stroke-width', '2.5');
    path.setAttribute('stroke-linecap', 'round');
    path.setAttribute('stroke-linejoin', 'round');
    svg.append(path);
    el.append(svg);

    const text = document.createElement('span');
    text.className = 'c-button__label';
    text.setAttribute('role', 'status'); // polite announcement
    if (label) text.textContent = label;
    el.append(text);
  });

  setTimeout(() => {
    morphWidth(el, () => {
      el.textContent = '';
      el.append(...original);
      delete el.dataset.success;
      el.disabled = originalDisabled;
    });
  }, duration);
}

/* ---- src/components/topbar.js ---- */
/**
 * c-topbar — mirrors Figma "title bar"/"top". DECISIONS.md #16 conventions.
 *
 * createTopbar({
 *   variant: 'root' | 'view' = 'view',
 *   title: string,                       // view title, or fallback text for root
 *   logo: boolean,                       // root variant: render the registry logo mark (Chats/home header only)
 *   onBack: (e) => void,                 // view variant: renders back icon-button
 *   backLabel: 'Back',                   // back button a11y label (SL in shells)
 *   actions: [{ icon: 'qrcode', label: 'Scan', onClick }]  // trailing icon-buttons
 * })
 */



function createTopbar({ variant = 'view', title = '', logo = false, onBack, backLabel = 'Back', actions = [] } = {}) {
  const el = document.createElement('header');
  el.className = 'c-topbar';
  el.dataset.variant = variant;

  if (variant === 'view' && onBack) {
    el.append(createButton({
      type: 'text', size: 44,
      icon: icon('arrow-left'),
      ariaLabel: backLabel,
      onClick: onBack,
    }));
  }

  const titleEl = document.createElement('div');
  titleEl.className = 'c-topbar__title';
  if (variant === 'root' && logo) {
    // logotype = inline mark (currentColor — inherits title ink, both modes) + wordmark
    const mark = icon('logo', { size: 28 });
    mark.classList.add('c-topbar__logo');
    const word = document.createElement('span');
    word.textContent = title || 'Spixi';
    titleEl.append(mark, word);
  } else {
    titleEl.textContent = title;
  }
  el.append(titleEl);

  if (actions.length) {
    const wrap = document.createElement('div');
    wrap.className = 'c-topbar__actions';
    for (const a of actions) {
      wrap.append(createButton({
        type: 'text', size: 44,
        icon: icon(a.icon),
        ariaLabel: a.label,
        onClick: a.onClick,
      }));
    }
    el.append(wrap);
  }

  return el;
}

/* ---- src/components/bottomnav.js ---- */
/**
 * c-bottomnav — mirrors Figma nav-bot/nav-item/indicator. DECISIONS.md #16.
 *
 * createBottomNav({
 *   items: [{ id, label, icon: 'messages', avatar: url|null, badge: number }],
 *   active: 'chats',
 *   ariaLabel: 'Main',                 // nav landmark label (SL in shells)
 *   onChange: (id) => void
 * })
 * Updates via free functions (button-style API):
 *   setNavActive(nav, id) · setNavBadge(nav, id, count)
 */



function createBottomNav({ items = [], active, ariaLabel = 'Main', onChange } = {}) {
  const el = document.createElement('nav');
  el.className = 'c-bottomnav';
  el.setAttribute('aria-label', ariaLabel);

  for (const item of items) {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'c-bottomnav__item';
    btn.dataset.id = item.id;

    const iconwrap = document.createElement('span');
    iconwrap.className = 'c-bottomnav__iconwrap';
    if (item.avatar) {
      const img = document.createElement('img');
      img.className = 'c-bottomnav__avatar';
      img.src = item.avatar;
      img.alt = '';
      iconwrap.append(img);
    } else {
      // outline = resting; -filled twin (when exported) crossfades in on select
      const outline = icon(item.icon);
      outline.classList.add('c-bottomnav__icon');
      iconwrap.append(outline);
      if (ICONS[item.icon + '-filled']) {
        iconwrap.dataset.dual = ''; // outline-fade only applies when a twin exists
        const filled = icon(item.icon + '-filled');
        filled.classList.add('c-bottomnav__icon--filled');
        filled.setAttribute('aria-hidden', 'true');
        iconwrap.append(filled);
      }
    }

    const badge = document.createElement('span');
    badge.className = 'c-bottomnav__badge';
    badge.hidden = true;
    iconwrap.append(badge);

    const label = document.createElement('span');
    label.className = 'c-bottomnav__label';
    label.textContent = item.label;

    btn.append(iconwrap, label);
    btn.addEventListener('click', () => {
      // active state lives in the DOM (setNavActive may be called externally)
      if (btn.hasAttribute('aria-current')) return; // already active — no re-fire
      setNavActive(el, item.id);
      if (onChange) onChange(item.id);
    });
    el.append(btn);
    if (item.badge) setNavBadge(el, item.id, item.badge);
  }

  if (active) setNavActive(el, active);
  return el;
}

/** Mark item `id` as the active destination; deselects the rest. */
function setNavActive(nav, id) {
  for (const btn of nav.querySelectorAll('.c-bottomnav__item')) {
    // 'page' = nav destination (vs 'true' on a selected chat-list row)
    if (btn.dataset.id === id) btn.setAttribute('aria-current', 'page');
    else btn.removeAttribute('aria-current');
  }
}

/** Set item `id`'s badge count (0 hides it). strings.unread overrides the a11y label suffix. */
function setNavBadge(nav, id, count, strings = {}) {
  const btn = nav.querySelector('.c-bottomnav__item[data-id="' + id + '"]');
  const badge = btn && btn.querySelector('.c-bottomnav__badge');
  if (!badge) return;
  if (count > 0) {
    badge.textContent = formatCount(count);
    badge.setAttribute('aria-label', count + ' ' + (strings.unread || 'unread'));
    badge.hidden = false;
  } else {
    badge.hidden = true;
    badge.removeAttribute('aria-label');
  }
}

/* ---- src/components/chip.js ---- */
/**
 * c-chip — filter/input chip (docs/chip-search-spec.md, DECISIONS #50).
 * Mirrors Figma chip/{small,large}; selected + disabled states are code-first
 * additions (🟡 #50). Dismissible chips: the WHOLE chip is the dismiss trigger
 * (no nested button); the X glyph is decorative.
 *
 * createChip({ label, size = 'large', selected = false, icon = null,
 *              dismissible = false, disabled = false, onClick, strings })
 * Updates via free function (#44): setChipSelected(el, selected)
 */


const CHIP_ICON_SIZE = { large: 18, small: 14 };   // leading (Figma)
const CHIP_DISMISS_SIZE = { large: 16, small: 14 }; // trailing (Figma)

function createChip({
  label = '', size = 'large', selected = false, icon: leading = null,
  dismissible = false, disabled = false, onClick, strings = {},
} = {}) {
  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-chip';
  el.dataset.size = size;
  el.disabled = disabled;

  if (leading) {
    const glyph = icon(leading, { size: CHIP_ICON_SIZE[size] || 18 });
    glyph.classList.add('c-chip__icon');
    el.append(glyph);
  }

  const text = document.createElement('span');
  text.className = 'c-chip__label';
  text.textContent = label;
  el.append(text);

  if (dismissible) {
    // whole-chip trigger; glyph is decorative (aria-hidden via icon factory)
    el.dataset.dismissible = '';
    el.setAttribute('aria-label', label + ' — ' + (strings.remove || 'remove'));
    const x = icon('x', { size: CHIP_DISMISS_SIZE[size] || 16 });
    x.classList.add('c-chip__dismiss');
    el.append(x);
  } else {
    // toggle (filter) semantics
    el.setAttribute('aria-pressed', String(!!selected));
  }

  if (onClick) el.addEventListener('click', onClick);
  return el;
}

/** Set a toggle chip's selected state (no-op on dismissible chips). */
function setChipSelected(el, selected) {
  if (!el.hasAttribute('aria-pressed')) return;
  el.setAttribute('aria-pressed', String(!!selected));
}

/* ---- src/components/search-field.js ---- */
/**
 * c-search-field — search input, specialization of Figma text-field/large
 * (docs/chip-search-spec.md, DECISIONS #51). Leading search glyph, clear
 * button appears only while text is present; Esc clears.
 *
 * createSearchField({ placeholder = 'Search', value = '', onInput, onSubmit,
 *                     ariaLabel, strings })
 * Free fns (#44): setSearchValue(el, v) · getSearchValue(el)
 */


function createSearchField({
  placeholder = 'Search', value = '', onInput, onSubmit, ariaLabel, strings = {},
} = {}) {
  const el = document.createElement('div');
  el.className = 'c-search-field';

  const glyph = icon('search', { size: 18 });
  glyph.classList.add('c-search-field__icon');

  const input = document.createElement('input');
  input.type = 'search';
  input.className = 'c-search-field__input';
  input.placeholder = placeholder;
  input.value = value;
  input.setAttribute('aria-label', ariaLabel || placeholder);

  const clear = document.createElement('button');
  clear.type = 'button';
  clear.className = 'c-search-field__clear';
  clear.setAttribute('aria-label', strings.clear || 'Clear search');
  clear.hidden = !value;
  clear.append(icon('x', { size: 18 }));

  const sync = () => { clear.hidden = input.value.length === 0; };

  input.addEventListener('input', () => {
    sync();
    if (onInput) onInput(input.value);
  });
  input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && onSubmit) onSubmit(input.value);
    else if (e.key === 'Escape' && input.value) {
      e.stopPropagation(); // Esc consumed by the clear, not by overlays above
      setSearchValue(el, '');
      if (onInput) onInput('');
    }
  });
  clear.addEventListener('click', () => {
    setSearchValue(el, '');
    if (onInput) onInput('');
    input.focus();
  });

  el.append(glyph, input, clear);
  return el;
}

/** Set the field's value (updates clear-button visibility). */
function setSearchValue(el, v) {
  v = v == null ? '' : String(v);
  const input = el.querySelector('.c-search-field__input');
  input.value = v;
  el.querySelector('.c-search-field__clear').hidden = v.length === 0;
}

/** Read the field's current value. */
function getSearchValue(el) {
  return el.querySelector('.c-search-field__input').value;
}

/* ---- src/components/highlight.js ---- */
/**
 * Text-match highlighting for search results (DECISIONS #52).
 * Wraps case-insensitive matches in span.c-highlight, walking TEXT nodes only —
 * structured children (mention/draft spans, icons) survive, and content is never
 * parsed as HTML (XSS-safe: text nodes in, text nodes out).
 *
 * setHighlights(rootEl, query) — query '' / null clears.
 */

function clearHighlights(rootEl) {
  for (const m of [...rootEl.querySelectorAll('.c-highlight')]) {
    m.replaceWith(document.createTextNode(m.textContent));
  }
  rootEl.normalize(); // merge the text nodes back together
}

function setHighlights(rootEl, query) {
  clearHighlights(rootEl);
  if (query == null || query === '') return;
  const q = String(query).toLocaleLowerCase();

  const walker = document.createTreeWalker(rootEl, NodeFilter.SHOW_TEXT);
  const textNodes = [];
  while (walker.nextNode()) textNodes.push(walker.currentNode);

  for (const node of textNodes) {
    const text = node.nodeValue;
    const lower = text.toLocaleLowerCase();
    let i = lower.indexOf(q);
    if (i === -1) continue;
    const frag = document.createDocumentFragment();
    let pos = 0;
    while (i !== -1) {
      if (i > pos) frag.append(document.createTextNode(text.slice(pos, i)));
      const mark = document.createElement('span');
      mark.className = 'c-highlight';
      mark.textContent = text.slice(i, i + q.length);
      frag.append(mark);
      pos = i + q.length;
      i = lower.indexOf(q, pos);
    }
    if (pos < text.length) frag.append(document.createTextNode(text.slice(pos)));
    node.replaceWith(frag);
  }
}

/* ---- src/components/badge.js ---- */
/**
 * c-badge — status badge, mirrors Figma badge type×weight (docs/tx-row-spec.md,
 * DECISIONS #54). Static display component — no interaction states.
 *
 * createBadge({ label, type = 'warning', weight = 'tonal', icon = null,
 *               trailingIcon = null })
 * type: warning | error | info | success | accent
 */


function createBadge({
  label = '', type = 'warning', weight = 'tonal', icon: leading = null, trailingIcon = null,
} = {}) {
  const el = document.createElement('span');
  el.className = 'c-badge';
  el.dataset.type = type;
  el.dataset.weight = weight;

  if (leading) el.append(icon(leading, { size: 16 }));

  const text = document.createElement('span');
  text.className = 'c-badge__label';
  text.textContent = label;
  el.append(text);

  if (trailingIcon) el.append(icon(trailingIcon, { size: 16 }));
  return el;
}

/* ---- src/components/txlist-item.js ---- */
/**
 * c-txlist-item — wallet transaction row (docs/tx-row-spec.md, DECISIONS #55).
 * Mirrors Figma tx list-chat type=sent|received|pending|failed; interaction
 * states are code-first (#43 coverage — Figma rows are static).
 * Bridge: addPaymentActivity(txid, received, counterparty, time, amount, fiat,
 * confirmed) — amount/fiat arrive pre-formatted, component stays dumb.
 *
 * createTxItem({ txid, direction = 'out'|'in', status = 'confirmed'|'pending'|
 *                'failed', name, timestamp, amount, fiat, onClick, strings })
 */




const BADGES = {
  pending: { type: 'warning', glyph: 'clock-hour-10', label: 'Pending', key: 'txPending' },
  failed: { type: 'error', glyph: 'alert-square-rounded', label: 'Failed', key: 'txFailed' },
};

function createTxItem({
  txid = '', direction = 'out', status = 'confirmed',
  name = '', timestamp, amount = '', fiat = '', onClick, strings = {},
} = {}) {
  // visual type: pending/failed override the direction presentation
  const type = status !== 'confirmed' ? status : (direction === 'in' ? 'received' : 'sent');

  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-txlist-item';
  el.dataset.type = type;
  if (txid) el.dataset.txid = txid;

  const circle = document.createElement('span');
  circle.className = 'c-txlist-item__direction';
  // labeled, not aria-hidden: direction is otherwise color/icon-only (amount
  // signs aren't guaranteed — failed rows ship unsigned per Figma)
  circle.append(icon(direction === 'in' ? 'arrow-down-left' : 'arrow-up-right', {
    size: 24,
    label: direction === 'in' ? (strings.received || 'Received') : (strings.sent || 'Sent'),
  }));
  el.append(circle);

  const content = document.createElement('span');
  content.className = 'c-txlist-item__content';
  const nameEl = document.createElement('span');
  nameEl.className = 'c-txlist-item__name';
  nameEl.textContent = name;
  content.append(nameEl);

  const row2 = document.createElement('span');
  row2.className = 'c-txlist-item__meta';
  const b = BADGES[status];
  if (b) {
    row2.append(createBadge({
      label: strings[b.key] || b.label, type: b.type, weight: 'tonal', icon: b.glyph,
    }));
  }
  if (timestamp != null) {
    const time = document.createElement('span');
    time.className = 'c-txlist-item__time u-tabular';
    time.textContent = formatTxTimestamp(timestamp);
    row2.append(time);
  }
  content.append(row2);
  el.append(content);

  const right = document.createElement('span');
  right.className = 'c-txlist-item__amounts';
  const amountEl = document.createElement('span');
  amountEl.className = 'c-txlist-item__amount u-tabular';
  amountEl.textContent = amount;
  const fiatEl = document.createElement('span');
  fiatEl.className = 'c-txlist-item__fiat u-tabular';
  fiatEl.textContent = fiat;
  right.append(amountEl, fiatEl);
  el.append(right);

  if (onClick) el.addEventListener('click', onClick);
  return el;
}

/* ---- src/components/overlay.js ---- */
/**
 * Shared overlay layer (docs/overlays-spec.md, DECISIONS #56): scrim, stack,
 * Esc/back dismissal, document-level focus containment, focus restore, host
 * scroll lock. Overlays mount into a HOST element (default document.body) so
 * the demo phone frames and real shells behave identically.
 *
 * Dismissal policy: Esc is the safe dismiss path (opts.escDismiss — sheet and
 * modal both default it true, per ARIA APG); opts.lightDismiss governs ONLY
 * scrim click (sheet true, modal false).
 */

const stack = []; // { el, scrim, opts, opener }
const overlayOpts = new WeakMap();    // el → opts, set by createSheet/createModal
const pendingRemoval = new WeakMap(); // el → finish-removal fn while its exit transition runs
let uid = 0;

/** Unique DOM id for overlay labelling (aria-labelledby / aria-describedby). */
function overlayId(prefix) { return prefix + '-' + (++uid); }

/** Attach open-time options to an overlay element (read by openOverlay). */
function setOverlayOpts(el, opts) { overlayOpts.set(el, opts); }

function focusables(el) {
  return [...el.querySelectorAll(
    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
  )].filter((n) => !n.disabled && !n.hidden);
}

// Document-level keydown while stack non-empty: Esc = safe dismiss of the top
// entry (when it allows it), Tab = trap within the top entry.
function onDocKeydown(e) {
  if (stack.length === 0) return;
  const top = stack[stack.length - 1];
  if (e.key === 'Escape') {
    if (top.opts.escDismiss) dismissOverlay(top.el);
    return;
  }
  if (e.key !== 'Tab') return;
  const f = focusables(top.el);
  if (f.length === 0) {
    e.preventDefault();
    top.el.focus({ preventScroll: true });
    return;
  }
  const first = f[0];
  const last = f[f.length - 1];
  const active = document.activeElement;
  if (!f.includes(active)) { // focus escaped (or sits on the overlay root) — pull it back in
    e.preventDefault();
    (e.shiftKey ? last : first).focus({ preventScroll: true });
  } else if (e.shiftKey && active === first) {
    e.preventDefault();
    last.focus({ preventScroll: true });
  } else if (!e.shiftKey && active === last) {
    e.preventDefault();
    first.focus({ preventScroll: true });
  }
}

// Document-level focus containment: anything focused outside the top overlay
// (and not its scrim) bounces back to the overlay's first focusable.
function onDocFocusin(e) {
  if (stack.length === 0) return;
  const top = stack[stack.length - 1];
  if (top.el.contains(e.target) || top.scrim.contains(e.target)) return;
  (focusables(top.el)[0] || top.el).focus({ preventScroll: true });
}

/** Open `el` as an overlay above a scrim inside `host`. Internal — sheets/modals wrap this. */
function openOverlay(el, opts) {
  if (stack.some((s) => s.el === el)) return; // already open — no-op

  // Element reuse: re-opened while its exit transition still runs — finish the
  // pending removal now (old scrim + listeners + host bookkeeping, no second
  // dismiss side effects) so a clean re-open proceeds.
  const finishPending = pendingRemoval.get(el);
  if (finishPending) finishPending();

  opts = opts || overlayOpts.get(el) || {};
  const host = opts.host || document.body;
  const opener = document.activeElement;

  const scrim = document.createElement('div');
  scrim.className = 'c-scrim';
  scrim.setAttribute('aria-hidden', 'true');
  if (opts.lightDismiss) scrim.addEventListener('click', () => dismissOverlay(el));

  host.append(scrim, el);
  host.dataset.overlayOpen = '';

  if (stack.length === 0) {
    document.addEventListener('keydown', onDocKeydown);
    document.addEventListener('focusin', onDocFocusin);
  }
  stack.push({ el, scrim, opts, opener });

  // enter transitions: two rAFs so initial styles paint first
  requestAnimationFrame(() => requestAnimationFrame(() => {
    scrim.dataset.open = '';
    el.dataset.open = '';
  }));

  const target = el.querySelector('[data-autofocus]') || focusables(el)[0] || el;
  target.focus({ preventScroll: true });
}

/** Dismiss a specific overlay (default: top of stack). Returns true if one closed. */
function dismissOverlay(el) {
  const i = el ? stack.findIndex((s) => s.el === el) : stack.length - 1;
  if (i === -1 || stack.length === 0) return false;
  const [entry] = stack.splice(i, 1);
  if (stack.length === 0) {
    document.removeEventListener('keydown', onDocKeydown);
    document.removeEventListener('focusin', onDocFocusin);
  }

  delete entry.scrim.dataset.open;
  delete entry.el.dataset.open;

  // focus restore — only if focus is ours to move (inside the closing overlay,
  // or already dropped to body); opener gone/unfocusable → new top overlay.
  const active = document.activeElement;
  if (entry.el.contains(active) || active === document.body) {
    const opener = entry.opener;
    if (opener && opener.isConnected && !opener.disabled && typeof opener.focus === 'function') {
      opener.focus({ preventScroll: true });
    } else {
      const top = stack[stack.length - 1];
      const f = top ? focusables(top.el) : [];
      if (f[0]) f[0].focus({ preventScroll: true });
    }
  }

  // remove after the exit transition (transitionend + timeout fallback, like #29 morph)
  let removed = false;
  let fallback;
  const onEnd = (e) => { if (e.target === entry.el) remove(); };
  const remove = () => {
    if (removed) return;
    removed = true;
    clearTimeout(fallback);
    entry.el.removeEventListener('transitionend', onEnd);
    pendingRemoval.delete(entry.el);
    entry.scrim.remove();
    entry.el.remove();
    const host = entry.opts.host || document.body; // scroll lock: recheck at removal time
    if (!stack.some((s) => (s.opts.host || document.body) === host)) {
      delete host.dataset.overlayOpen;
    }
    if (entry.opts.onDismiss) entry.opts.onDismiss();
  };
  entry.el.addEventListener('transitionend', onEnd);
  fallback = setTimeout(remove, 400); // > --duration-200; covers reduced-motion 0ms
  pendingRemoval.set(entry.el, remove);
  return true;
}

/** Shell onBack hook: dismiss the top overlay if any. True = consumed. */
function dismissTopOverlay() {
  if (stack.length === 0) return false;
  return dismissOverlay(stack[stack.length - 1].el);
}

/* ---- src/components/sheet.js ---- */
/**
 * c-sheet — bottom sheet (docs/overlays-spec.md, DECISIONS #56). Replaces the
 * bridge-era toggleAnimatedSlider menus. z-40, light-dismiss by default.
 *
 * createSheet({ title, content, host, lightDismiss = true, escDismiss = true,
 *               onDismiss, strings })
 *   lightDismiss — scrim click closes (sheet default: true)
 *   escDismiss   — Esc closes (default: true; safe dismiss path, ARIA APG)
 *   strings.sheet — aria-label fallback when there is no title ('Menu')
 * openSheet(el) / closeSheet(el) free fns (#44).
 */


function createSheet({
  title = '', content = null, host, lightDismiss = true, escDismiss = true,
  onDismiss, strings = {},
} = {}) {
  const el = document.createElement('section');
  el.className = 'c-sheet';
  el.setAttribute('role', 'dialog');
  el.setAttribute('aria-modal', 'true');
  el.tabIndex = -1;

  const handle = document.createElement('span');
  handle.className = 'c-sheet__handle';
  handle.setAttribute('aria-hidden', 'true');
  el.append(handle);

  if (title) {
    const t = document.createElement('h2');
    t.className = 'c-sheet__title t-heading-xs';
    t.textContent = title;
    t.id = overlayId('c-sheet-title');
    el.setAttribute('aria-labelledby', t.id);
    el.append(t);
  } else {
    el.setAttribute('aria-label', strings.sheet || 'Menu');
  }

  const body = document.createElement('div');
  body.className = 'c-sheet__content';
  if (content) body.append(content);
  el.append(body);

  setOverlayOpts(el, { host, lightDismiss, escDismiss, onDismiss });
  return el;
}

function openSheet(el) { openOverlay(el); }
function closeSheet(el) { dismissOverlay(el); }

/* ---- src/components/modal.js ---- */
/**
 * c-modal — dialog (docs/overlays-spec.md, DECISIONS #56). Replaces
 * showModalDialog. z-50; scrim click does NOT dismiss by default
 * (confirmations are explicit) but Esc DOES (safe dismiss path, ARIA APG).
 * Destructive confirms: role=alertdialog + autofocus the SAFE action.
 *
 * createModal({ title, body, actions, role = 'dialog', host,
 *               lightDismiss = false, escDismiss = true, onDismiss, strings })
 *   actions: [{ label, type = 'text'|'fill'|…, intent, onClick, autofocus }]
 *   an action returning false from onClick keeps the modal open.
 *   lightDismiss — scrim click closes (modal default: false)
 *   escDismiss   — Esc closes (default: true)
 *   strings.modal — aria-label fallback when there is no title ('Dialog')
 * openModal(el) / closeModal(el) free fns (#44).
 */



function createModal({
  title = '', body = '', actions = [], role = 'dialog', host,
  lightDismiss = false, escDismiss = true, onDismiss, strings = {},
} = {}) {
  const el = document.createElement('section');
  el.className = 'c-modal';
  el.setAttribute('role', role);
  el.setAttribute('aria-modal', 'true');
  el.tabIndex = -1;

  if (title) {
    const t = document.createElement('h2');
    t.className = 'c-modal__title t-heading-xs';
    t.textContent = title;
    t.id = overlayId('c-modal-title');
    el.setAttribute('aria-labelledby', t.id);
    el.append(t);
  } else {
    el.setAttribute('aria-label', strings.modal || 'Dialog');
    if (role === 'alertdialog') {
      console.warn('c-modal: role=alertdialog without a title — SRs announce alert dialogs by their label; provide one');
    }
  }

  if (body) {
    const b = document.createElement('p');
    b.className = 'c-modal__body';
    b.textContent = body;
    b.id = overlayId('c-modal-body');
    el.setAttribute('aria-describedby', b.id);
    el.append(b);
  }

  if (actions.length) {
    const row = document.createElement('div');
    row.className = 'c-modal__actions';
    for (const a of actions) {
      const btn = createButton({
        label: a.label, type: a.type || 'text', intent: a.intent, size: 44,
        onClick: () => {
          const keep = a.onClick ? a.onClick() : undefined;
          if (keep !== false) dismissOverlay(el);
        },
      });
      if (a.autofocus) btn.dataset.autofocus = '';
      row.append(btn);
    }
    el.append(row);
  }

  setOverlayOpts(el, { host, lightDismiss, escDismiss, onDismiss });
  return el;
}

function openModal(el) { openOverlay(el); }
function closeModal(el) { dismissOverlay(el); }

/* ---- src/components/banner.js ---- */
function createWarningBanner({ strings = {} } = {}) {
  const el = document.createElement('div');
  el.className = 'c-banner';
  el.setAttribute('role', 'status');
  el.setAttribute('aria-label', strings.status || 'Status');
  const inner = document.createElement('span');
  inner.className = 'c-banner__inner';
  inner.append(icon('alert-square-rounded', { size: 20 }));
  const text = document.createElement('span');
  text.className = 'c-banner__text';
  inner.append(text);
  el.append(inner);
  return el;
}
function setWarning(el, message) {
  const text = el.querySelector('.c-banner__text');
  if (message) {
    text.textContent = message;
    el.dataset.open = '';
  } else {
    delete el.dataset.open;
  }
}

/* ---- src/components/toast.js ---- */
const TONE_GLYPHS = { info: 'info-circle', success: 'check', error: 'alert-square-rounded' };
const toastHostState = new WeakMap(); // host → { current, queue }
function showToast(opts = {}) {
  const host = opts.host || document.body;
  let state = toastHostState.get(host);
  if (!state) { state = { current: null, queue: [] }; toastHostState.set(host, state); }
  if (state.current) {
    const last = state.queue[state.queue.length - 1];
    const dup = last && last.text === opts.text && last.tone === opts.tone;
    if (!dup) {
      state.queue.push(opts);
      if (state.queue.length > 2) state.queue.shift();
    }
    return () => {
      const i = state.queue.indexOf(opts);
      if (i !== -1) state.queue.splice(i, 1);
    };
  }
  return presentToast(host, state, opts);
}
function presentToast(host, state, { text = '', tone = 'info', duration = 3500 } = {}) {
  const el = document.createElement('div');
  el.className = 'c-toast';
  el.dataset.tone = tone;
  el.setAttribute('role', 'status');
  el.append(icon(TONE_GLYPHS[tone] || TONE_GLYPHS.info, { size: 20 }));
  const t = document.createElement('span');
  t.className = 'c-toast__text';
  t.textContent = text;
  el.append(t);
  host.append(el);
  state.current = el;
  requestAnimationFrame(() => requestAnimationFrame(() => { el.dataset.open = ''; }));
  let removed = false;
  let exitFallback;
  const remove = () => {
    if (removed) return;
    removed = true;
    clearTimeout(exitFallback);
    el.remove();
    state.current = null;
    const next = state.queue.shift();
    if (next) presentToast(host, state, next);
  };
  const dismiss = () => {
    if (removed) return;
    clearTimeout(autoTimer);
    if (el.dataset.open === undefined) { remove(); return; }
    delete el.dataset.open;
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) { remove(); return; }
    el.addEventListener('transitionend', (e) => { if (e.target === el) remove(); });
    exitFallback = setTimeout(remove, 400);
  };
  el.addEventListener('click', dismiss);
  const autoTimer = setTimeout(dismiss, duration);
  return dismiss;
}

/* ---- src/components/callbar.js ---- */
const callBars = new WeakMap(); // host → { el, timer }
function formatCallDuration(ms) {
  const total = Math.max(0, Math.floor(ms / 1000));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const mm = h > 0 ? String(m).padStart(2, '0') : String(m);
  const ss = String(s).padStart(2, '0');
  return (h > 0 ? h + ':' + mm : mm) + ':' + ss;
}
function showCallBar({
  text = '', startedAt = Date.now(), onReturn, onHangUp,
  host = document.body, strings = {},
} = {}) {
  const existing = callBars.get(host);
  if (existing) {
    existing.startedAt = startedAt;
    existing.el.querySelector('.c-callbar__text').textContent = text;
    existing.el.querySelector('.c-callbar__time').textContent =
      formatCallDuration(Date.now() - startedAt);
    return existing.el;
  }
  const el = document.createElement('div');
  el.className = 'c-callbar';
  const main = document.createElement('button');
  main.type = 'button';
  main.className = 'c-callbar__main';
  main.setAttribute('aria-label', strings.returnToCall || 'Return to call');
  main.append(icon('phone', { size: 20 }));
  const label = document.createElement('span');
  label.className = 'c-callbar__text';
  label.textContent = text;
  main.append(label);
  const time = document.createElement('span');
  time.className = 'c-callbar__time u-tabular';
  time.textContent = formatCallDuration(Date.now() - startedAt);
  main.append(time);
  if (onReturn) main.addEventListener('click', onReturn);
  el.append(main);
  const hangup = document.createElement('button');
  hangup.type = 'button';
  hangup.className = 'c-callbar__hangup';
  hangup.setAttribute('aria-label', strings.hangUp || 'Hang up');
  hangup.append(icon('phone-end', { size: 20 }));
  if (onHangUp) hangup.addEventListener('click', onHangUp);
  el.append(hangup);
  host.append(el);
  requestAnimationFrame(() => requestAnimationFrame(() => {
    if (el.isConnected && callBars.get(host) && callBars.get(host).el === el) el.dataset.open = '';
  }));
  const entry = { el, startedAt, timer: 0 };
  entry.timer = setInterval(() => {
    time.textContent = formatCallDuration(Date.now() - entry.startedAt);
  }, 1000);
  callBars.set(host, entry);
  return el;
}
function hideCallBar(host = document.body) {
  const entry = callBars.get(host);
  if (!entry) return false;
  callBars.delete(host);
  clearInterval(entry.timer);
  const { el } = entry;
  if (el.dataset.open === undefined) { el.remove(); return true; }
  delete el.dataset.open;
  let removed = false;
  const remove = () => { if (!removed) { removed = true; el.remove(); } };
  el.addEventListener('transitionend', (e) => { if (e.target === el) remove(); });
  setTimeout(remove, 400);
  return true;
}

/* ---- src/components/message-bubble.js ---- */
function bubbleTime(ts) {
  const locale = document.documentElement.lang || undefined;
  return new Date(ts).toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' });
}
function createMessageBubble({
  direction = 'received',
  position = 'single',
  text = '',
  timestamp = null,
  status = null,
  sender = null,
  showAvatar = false,
  name = '',
  address = '',
  avatar = null,
  strings = {},
} = {}) {
  const row = document.createElement('div');
  row.className = 'c-bubble-row';
  row.dataset.direction = direction;
  row.dataset.position = position;
  if (direction === 'received' && (showAvatar || sender !== null)) {
    const gutter = document.createElement('span');
    gutter.className = 'c-bubble-row__gutter';
    if (showAvatar && (position === 'last' || position === 'single')) {
      gutter.append(createAvatar({ src: avatar, name, address, size: 24 }));
    }
    row.append(gutter);
  }
  const el = document.createElement('div');
  el.className = 'c-bubble';
  if (sender && (position === 'first' || position === 'single')) {
    const s = document.createElement('span');
    s.className = 'c-bubble__sender';
    s.textContent = sender;
    s.style.setProperty('--sender-h', hashHue(address || name || sender));
    el.append(s);
  }
  const body = document.createElement('span');
  body.className = 'c-bubble__text';
  body.textContent = text;
  el.append(body);
  const meta = document.createElement('span');
  meta.className = 'c-bubble__meta u-tabular';
  if (timestamp != null) {
    const t = document.createElement('time');
    t.setAttribute('datetime', new Date(timestamp).toISOString());
    t.textContent = bubbleTime(timestamp);
    meta.append(t);
  }
  if (direction === 'sent' && status) {
    const st = createStatusIcon(status);
    if (st) {
      st.setAttribute('width', 14);
      st.setAttribute('height', 14);
      st.removeAttribute('aria-hidden');
      st.setAttribute('role', 'img');
      st.setAttribute('aria-label', strings['status-' + status] || status);
      meta.append(st);
    }
  }
  if (meta.childNodes.length) el.append(meta);
  row.append(el);
  return row;
}
function createDateSeparator(ts, strings = {}, now = Date.now()) {
  const el = document.createElement('div');
  el.className = 'c-datesep';
  el.setAttribute('role', 'separator');
  const pill = document.createElement('span');
  pill.className = 'c-datesep__pill';
  pill.textContent = dayBucketLabel(ts, strings, now, strings.today || 'Today');
  el.append(pill);
  return el;
}

/* ---- BATCH 1b SUPERSEDE SECTION (manual append — PC mirror can't run the
   builder; `node scripts/build-demo-bundle.mjs` on the Mac normalizes this).
   Later function declarations override the earlier ones above. ---- */

/* ---- src/components/topbar.js (chat variant + setTopbarSub) ---- */
function createTopbar({ variant = 'view', title = '', logo = false, identity = null, onBack, backLabel = 'Back', actions = [] } = {}) {
  const el = document.createElement('header');
  el.className = 'c-topbar';
  el.dataset.variant = variant;
  if ((variant === 'view' || variant === 'chat') && onBack) {
    el.append(createButton({
      type: 'text', size: 44,
      icon: icon('arrow-left'),
      ariaLabel: backLabel,
      onClick: onBack,
    }));
  }
  if (variant === 'chat' && identity) {
    el.append(createAvatar({
      src: identity.avatar, name: identity.name, address: identity.address,
      size: 40, online: !!identity.online,
    }));
    const id = document.createElement('div');
    id.className = 'c-topbar__identity';
    const nameEl = document.createElement('span');
    nameEl.className = 'c-topbar__name';
    nameEl.textContent = identity.name || identity.address || '';
    const subEl = document.createElement('span');
    subEl.className = 'c-topbar__sub';
    subEl.setAttribute('aria-live', 'polite');
    subEl.textContent = identity.sub || '';
    id.append(nameEl, subEl);
    el.append(id);
  } else {
    const titleEl = document.createElement('div');
    titleEl.className = 'c-topbar__title';
    if (variant === 'root' && logo) {
      const mark = icon('logo', { size: 28 });
      mark.classList.add('c-topbar__logo');
      const word = document.createElement('span');
      word.textContent = title || 'Spixi';
      titleEl.append(mark, word);
    } else {
      titleEl.textContent = title;
    }
    el.append(titleEl);
  }
  if (actions.length) {
    const wrap = document.createElement('div');
    wrap.className = 'c-topbar__actions';
    for (const a of actions) {
      wrap.append(createButton({
        type: 'text', size: 44,
        icon: icon(a.icon),
        ariaLabel: a.label,
        onClick: a.onClick,
      }));
    }
    el.append(wrap);
  }
  return el;
}
function setTopbarSub(el, text) {
  const sub = el.querySelector('.c-topbar__sub');
  if (sub) sub.textContent = text || '';
}

/* ---- src/components/message-bubble.js (failed + onRetry) ---- */
function createMessageBubble({
  direction = 'received',
  position = 'single',
  text = '',
  timestamp = null,
  status = null,
  sender = null,
  showAvatar = false,
  name = '',
  address = '',
  avatar = null,
  onRetry = null,
  strings = {},
} = {}) {
  const row = document.createElement('div');
  row.className = 'c-bubble-row';
  row.dataset.direction = direction;
  row.dataset.position = position;
  if (direction === 'received' && (showAvatar || sender !== null)) {
    const gutter = document.createElement('span');
    gutter.className = 'c-bubble-row__gutter';
    if (showAvatar && (position === 'last' || position === 'single')) {
      gutter.append(createAvatar({ src: avatar, name, address, size: 24 }));
    }
    row.append(gutter);
  }
  const el = document.createElement('div');
  el.className = 'c-bubble';
  if (sender && (position === 'first' || position === 'single')) {
    const s = document.createElement('span');
    s.className = 'c-bubble__sender';
    s.textContent = sender;
    s.style.setProperty('--sender-h', hashHue(address || name || sender));
    el.append(s);
  }
  const body = document.createElement('span');
  body.className = 'c-bubble__text';
  body.textContent = text;
  el.append(body);
  const meta = document.createElement('span');
  meta.className = 'c-bubble__meta u-tabular';
  if (timestamp != null) {
    const t = document.createElement('time');
    t.setAttribute('datetime', new Date(timestamp).toISOString());
    t.textContent = bubbleTime(timestamp);
    meta.append(t);
  }
  if (direction === 'sent' && status) {
    const st = createStatusIcon(status);
    if (st) {
      st.setAttribute('width', 14);
      st.setAttribute('height', 14);
      st.removeAttribute('aria-hidden');
      st.setAttribute('role', 'img');
      st.setAttribute('aria-label', strings['status-' + status] || status);
      meta.append(st);
    }
  }
  if (meta.childNodes.length) el.append(meta);
  if (direction === 'sent' && status === 'failed') {
    row.dataset.failed = '';
    const retry = document.createElement('button');
    retry.type = 'button';
    retry.className = 'c-bubble-retry';
    retry.setAttribute('aria-label', strings.retry || 'Retry sending');
    retry.append(icon('rotate-clockwise-2', { size: 16 }));
    if (onRetry) retry.addEventListener('click', onRetry);
    const line = document.createElement('div');
    line.className = 'c-bubble-line';
    line.append(retry, el);
    const stack = document.createElement('div');
    stack.className = 'c-bubble-stack';
    stack.append(line);
    const note = document.createElement('span');
    note.className = 'c-bubble-failnote';
    note.textContent = strings.notDelivered || 'Not delivered · Tap to retry';
    if (onRetry) note.addEventListener('click', onRetry);
    stack.append(note);
    row.append(stack);
    return row;
  }
  row.append(el);
  return row;
}

/* ---- src/components/composer.js ---- */
const COMPOSER_MAX_LINES = 5;
function createComposer({
  placeholder = 'Message',
  voice = false,
  onSend,
  onAttach,
  onTyping,
  onRecord,
  strings = {},
} = {}) {
  const el = document.createElement('div');
  el.className = 'c-composer';
  const field = document.createElement('div');
  field.className = 'c-composer__field';
  const attach = document.createElement('button');
  attach.type = 'button';
  attach.className = 'c-composer__attach';
  attach.setAttribute('aria-label', strings.attach || 'Attach');
  attach.append(icon('circle-plus', { size: 24 }));
  if (onAttach) attach.addEventListener('click', onAttach);
  field.append(attach);
  const input = document.createElement('textarea');
  input.className = 'c-composer__input';
  input.rows = 1;
  input.placeholder = placeholder;
  input.setAttribute('aria-label', placeholder);
  field.append(input);
  el.append(field);
  const action = document.createElement('button');
  action.type = 'button';
  action.className = 'c-composer__action';
  el.append(action);
  const sendIcon = () => { action.textContent = ''; action.append(icon('send-2', { size: 20 })); };
  const micIcon = () => { action.textContent = ''; action.append(icon('microphone', { size: 20 })); };
  const hasText = () => input.value.trim().length > 0;
  const syncAction = () => {
    if (voice && !hasText()) {
      micIcon();
      action.dataset.mode = 'mic';
      action.disabled = false;
      action.setAttribute('aria-label', strings.record || 'Record voice message');
    } else {
      sendIcon();
      action.dataset.mode = 'send';
      action.disabled = !hasText();
      action.setAttribute('aria-label', strings.send || 'Send');
    }
  };
  const grow = () => {
    input.style.height = 'auto';
    const cs = getComputedStyle(input);
    const line = parseInt(cs.lineHeight, 10) || 24;
    const pad = (parseInt(cs.paddingTop, 10) || 0) + (parseInt(cs.paddingBottom, 10) || 0);
    input.style.height = Math.min(input.scrollHeight, line * COMPOSER_MAX_LINES + pad) + 'px';
  };
  const send = () => {
    const text = input.value.trim();
    if (!text) return;
    if (onSend) onSend(text);
    input.value = '';
    grow();
    syncAction();
    input.focus();
  };
  input.addEventListener('input', (e) => {
    grow();
    syncAction();
    if (onTyping && e.isTrusted) onTyping();
  });
  input.addEventListener('keydown', (e) => {
    if (e.isComposing || e.keyCode === 229) return;
    if (e.key === 'Enter' && !e.shiftKey && matchMedia('(hover: hover)').matches) {
      e.preventDefault();
      send();
    }
  });
  action.addEventListener('click', () => {
    if (action.dataset.mode === 'mic') { if (onRecord) onRecord(); }
    else send();
  });
  syncAction();
  return el;
}
function clearComposer(el) {
  const input = el.querySelector('.c-composer__input');
  if (!input) return;
  input.value = '';
  input.style.height = 'auto';
  input.dispatchEvent(new Event('input'));
}

/* ---- src/components/typed-bubbles.js ---- */
function cardTime(ts) {
  const locale = document.documentElement.lang || undefined;
  return new Date(ts).toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' });
}
function card(direction, title, timestamp, modifier) {
  const row = document.createElement('div');
  row.className = 'c-bubble-row';
  row.dataset.direction = direction;
  row.dataset.position = 'single';
  const el = document.createElement('div');
  el.className = 'c-tcard';
  if (modifier) el.dataset.kind = modifier;
  const head = document.createElement('div');
  head.className = 'c-tcard__head';
  const t = document.createElement('span');
  t.className = 'c-tcard__title';
  t.textContent = title;
  head.append(t);
  if (timestamp != null) {
    const time = document.createElement('time');
    time.className = 'c-tcard__time u-tabular';
    time.setAttribute('datetime', new Date(timestamp).toISOString());
    time.textContent = cardTime(timestamp);
    head.append(time);
  }
  el.append(head);
  row.append(el);
  return { row, el };
}
function actionsRow(...buttons) {
  const r = document.createElement('div');
  r.className = 'c-tcard__actions';
  for (const b of buttons) if (b) { b.dataset.width = 'full'; r.append(b); }
  return r;
}
function detailsLink(onDetails, strings) {
  const wrap = document.createElement('div');
  wrap.className = 'c-tcard__details';
  const btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'c-tcard__details-btn';
  btn.append(document.createTextNode(strings.details || 'Details'), icon('chevron-right', { size: 16 }));
  if (onDetails) btn.addEventListener('click', onDetails);
  wrap.append(btn);
  return wrap;
}
function createPaymentBubble({
  role = 'request-in',
  amount = '',
  fiat = '',
  status = 'actionable',
  insufficient = false,
  timestamp = null,
  onPay, onDecline, onCancel, onRetry, onDetails,
  strings = {},
} = {}) {
  const direction = (role === 'request-in' || role === 'received') ? 'received' : 'sent';
  const titles = {
    'request-in': strings.paymentRequest || 'Payment request',
    'request-out': strings.youRequested || 'You requested',
    sent: status === 'failed' ? (strings.paymentFailed || 'Payment failed') : (strings.paymentSent || 'Payment sent'),
    received: strings.paymentReceived || 'Payment received',
  };
  const { row, el } = card(direction, titles[role], timestamp, 'payment');
  row.dataset.status = status;
  const amountEl = document.createElement('div');
  amountEl.className = 'c-tcard__amount u-tabular';
  amountEl.dataset.tone =
    status === 'completed' ? (String(amount).startsWith('+') ? 'positive' : 'neutral')
    : (status === 'declined' || status === 'canceled' || status === 'failed') ? 'void'
    : 'pending';
  amountEl.append(document.createTextNode(amount + ' '));
  const unit = document.createElement('span');
  unit.className = 'c-tcard__unit';
  unit.textContent = 'IXI';
  amountEl.append(unit);
  el.append(amountEl);
  if (fiat) {
    const f = document.createElement('div');
    f.className = 'c-tcard__fiat u-tabular';
    if (status === 'declined' || status === 'canceled' || status === 'failed') f.dataset.tone = 'void';
    f.textContent = fiat;
    el.append(f);
  }
  const BADGES = {
    pending: ['warning', strings.pending || 'Pending', 'clock-hour-10'],
    failed: ['error', strings.failed || 'Failed', 'alert-square-rounded'],
    completed: ['success', strings.completed || 'Completed', 'check'],
    declined: ['error', strings.declined || 'Declined', 'cancel'],
    canceled: ['info', strings.canceled || 'Canceled', 'circle-x'],
  };
  if (BADGES[status]) {
    const [type, label, glyph] = BADGES[status];
    const wrap = document.createElement('div');
    wrap.className = 'c-tcard__badge';
    wrap.append(createBadge({ type, weight: 'tonal', label, icon: glyph }));
    el.append(wrap);
  }
  if (role === 'request-in' && (status === 'actionable' || status === 'processing' || status === 'failed')) {
    const decline = createButton({ label: strings.decline || 'Decline', type: 'outline', size: 32, onClick: onDecline, disabled: status === 'processing' });
    const pay = status === 'failed'
      ? createButton({ label: strings.retry || 'Retry', type: 'fill', size: 32, icon: icon('rotate-clockwise-2', { size: 16 }), onClick: onRetry })
      : createButton({ label: strings.pay || 'Pay', type: 'fill', size: 32, icon: icon('check', { size: 16 }), onClick: onPay, disabled: insufficient, loading: status === 'processing' });
    el.append(actionsRow(decline, pay));
    if (insufficient) {
      const note = document.createElement('div');
      note.className = 'c-tcard__note';
      note.textContent = strings.insufficient || 'Insufficient balance to pay.';
      el.append(note);
    }
  } else if (role === 'request-out' && status === 'pending') {
    el.append(actionsRow(createButton({ label: strings.cancelRequest || 'Cancel request', type: 'outline', size: 32, onClick: onCancel })));
  } else if (role === 'sent' && status === 'failed') {
    el.append(actionsRow(createButton({ label: strings.retry || 'Retry', type: 'fill', size: 32, icon: icon('rotate-clockwise-2', { size: 16 }), onClick: onRetry })));
  } else if (status === 'completed' || ((role === 'sent' || role === 'received') && status === 'pending')) {
    el.append(detailsLink(onDetails, strings));
  }
  return row;
}
function createAppBubble({
  name = '',
  iconUrl = null,
  state = 'invite',
  direction = null,
  timestamp = null,
  onJoin, onDecline, onLaunch, onCancel, onGet, onEnd, onResume,
  strings = {},
} = {}) {
  const dir = direction || (state === 'invited' ? 'sent' : 'received');
  const title = (state === 'in-session' || state === 'ended')
    ? (strings.appSession || 'App session')
    : (strings.appInvite || 'App invite');
  const { row, el } = card(dir, title, timestamp, 'app');
  const id = document.createElement('div');
  id.className = 'c-tcard__app';
  const ic = document.createElement('span');
  ic.className = 'c-tcard__app-icon';
  if (iconUrl) {
    const img = document.createElement('img');
    img.src = iconUrl;
    img.alt = '';
    ic.append(img);
  } else {
    ic.append(icon('rocket', { size: 24 }));
  }
  const col = document.createElement('span');
  col.className = 'c-tcard__app-info';
  const nm = document.createElement('span');
  nm.className = 'c-tcard__app-name';
  nm.textContent = name;
  const sub = document.createElement('span');
  sub.className = 'c-tcard__app-sub';
  sub.textContent = {
    invite: strings.invitedYou || 'Invited you to join',
    invited: strings.youInvited || 'You have sent an invite',
    missing: strings.invitedYou || 'Invited you to join',
    'in-session': strings.inSession || 'In session',
    ended: strings.sessionEnded || 'Session ended',
  }[state];
  col.append(nm, sub);
  id.append(ic, col);
  el.append(id);
  if (state === 'invite') {
    el.append(actionsRow(
      createButton({ label: strings.decline || 'Decline', type: 'outline', size: 32, onClick: onDecline }),
      createButton({ label: strings.join || 'Join', type: 'fill', size: 32, icon: icon('check', { size: 16 }), onClick: onJoin }),
    ));
  } else if (state === 'invited') {
    el.append(actionsRow(
      createButton({ label: strings.cancel || 'Cancel', type: 'outline', size: 32, onClick: onCancel }),
      createButton({ label: strings.launchApp || 'Launch app', type: 'fill', size: 32, icon: icon('rocket', { size: 16 }), onClick: onLaunch }),
    ));
  } else if (state === 'missing') {
    el.append(actionsRow(createButton({ label: strings.getApp || 'Get app', type: 'fill', size: 32, icon: icon('download', { size: 16 }), onClick: onGet })));
  } else if (state === 'in-session') {
    el.append(actionsRow(
      createButton({ label: strings.endSession || 'End session', type: 'outline', size: 32, onClick: onEnd }),
      createButton({ label: strings.resume || 'Resume', type: 'fill', size: 32, icon: icon('player-play', { size: 16 }), onClick: onResume }),
    ));
  }
  return row;
}
function createCallBubble({
  missed = false,
  direction = 'received',
  directionLabel = '',
  duration = '',
  timestamp = null,
  onCallBack,
  strings = {},
} = {}) {
  const { row, el } = card(direction,
    missed ? (strings.missedCall || 'Missed voice call') : (strings.voiceCall || 'Voice call'),
    timestamp, 'call');
  if (missed) row.dataset.missed = '';
  const head = el.querySelector('.c-tcard__title');
  head.insertAdjacentElement('afterbegin', icon(missed ? 'phone-off' : 'phone', { size: 18 }));
  if (missed) {
    const sub = document.createElement('button');
    sub.type = 'button';
    sub.className = 'c-tcard__call-back';
    sub.textContent = strings.tapToCallBack || 'Tap to call back';
    if (onCallBack) sub.addEventListener('click', onCallBack);
    el.append(sub);
  } else {
    const meta = document.createElement('div');
    meta.className = 'c-tcard__call-meta u-tabular';
    meta.textContent = directionLabel + (duration ? ' · ' + duration : '');
    el.append(meta);
    const wrap = detailsLink(onCallBack, { details: strings.callBack || 'Call back' });
    el.append(wrap);
  }
  return row;
}
function createFileBubble({
  direction = 'received',
  name = '',
  meta = '',
  state = 'complete',
  progress = 0,
  timestamp = null,
  onAccept, onOpen, onRetry,
  strings = {},
} = {}) {
  const row = document.createElement('div');
  row.className = 'c-bubble-row';
  row.dataset.direction = direction;
  row.dataset.position = 'single';
  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-fbubble';
  el.dataset.state = state;
  const act = state === 'offer' ? onAccept : state === 'failed' ? onRetry : state === 'complete' ? onOpen : null;
  if (act) el.addEventListener('click', act);
  else if (state === 'progress') el.disabled = true;
  el.setAttribute('aria-label',
    (state === 'offer' ? (strings.download || 'Download')
      : state === 'failed' ? (strings.retry || 'Retry')
      : state === 'progress' ? (strings.downloading || 'Downloading')
      : (strings.open || 'Open'))
    + ' ' + name);
  const ic = document.createElement('span');
  ic.className = 'c-fbubble__icon';
  ic.append(icon(state === 'failed' ? 'rotate-clockwise-2' : state === 'offer' ? 'download' : 'file-isr', { size: 20 }));
  el.append(ic);
  const col = document.createElement('span');
  col.className = 'c-fbubble__info';
  const nm = document.createElement('span');
  nm.className = 'c-fbubble__name';
  nm.textContent = name;
  const mt = document.createElement('span');
  mt.className = 'c-fbubble__meta';
  mt.textContent = state === 'failed' ? (strings.transferFailed || 'Transfer failed · Tap to retry') : meta;
  col.append(nm, mt);
  if (state === 'progress') {
    const track = document.createElement('span');
    track.className = 'c-fbubble__track';
    track.setAttribute('role', 'progressbar');
    track.setAttribute('aria-valuemin', '0');
    track.setAttribute('aria-valuemax', '100');
    track.setAttribute('aria-valuenow', String(Math.max(0, Math.min(100, progress))));
    const fill = document.createElement('span');
    fill.className = 'c-fbubble__fill';
    fill.style.width = Math.max(0, Math.min(100, progress)) + '%';
    track.append(fill);
    col.append(track);
  }
  el.append(col);
  if (timestamp != null) {
    const time = document.createElement('time');
    time.className = 'c-fbubble__time u-tabular';
    time.setAttribute('datetime', new Date(timestamp).toISOString());
    time.textContent = cardTime(timestamp);
    el.append(time);
  }
  row.append(el);
  return row;
}
function setFileProgress(rowEl, progress, opts = {}) {
  const p = Math.max(0, Math.min(100, progress));
  const fill = rowEl.querySelector('.c-fbubble__fill');
  if (fill) fill.style.width = p + '%';
  const track = rowEl.querySelector('.c-fbubble__track');
  if (track) track.setAttribute('aria-valuenow', String(p));
  const metaEl = rowEl.querySelector('.c-fbubble__meta');
  if (metaEl && opts.meta) metaEl.textContent = opts.meta;
  const bubble = rowEl.querySelector('.c-fbubble');
  const finalState = opts.state || (p >= 100 ? 'complete' : null);
  if (bubble && finalState && bubble.dataset.state !== finalState) {
    bubble.dataset.state = finalState;
    bubble.disabled = false;
    if (track) track.remove();
  }
}
function createUnreadDivider(strings = {}) {
  const el = document.createElement('div');
  el.className = 'c-unread-divider';
  el.setAttribute('role', 'separator');
  const label = document.createElement('span');
  label.textContent = strings.unreadMessages || 'Unread messages';
  el.append(label);
  return el;
}

/* ---- src/components/avatar.js (24/40/48 token sizes — supersede parity) ---- */
function createAvatar({ src = null, name = '', address = '', size = 48, online = false } = {}) {
  const el = document.createElement('span');
  el.className = 'c-avatar';
  el.dataset.size = String(size);
  if (size !== 24 && size !== 40 && size !== 48) {
    el.style.width = size + 'px';
    el.style.height = size + 'px';
  }
  if (src) {
    const img = document.createElement('img');
    img.className = 'c-avatar__img';
    img.src = src;
    img.alt = '';
    el.append(img);
  } else {
    const hue = hashHue(address || name);
    el.dataset.placeholder = '';
    el.style.setProperty('--av-h1', hue);
    el.style.setProperty('--av-h2', (hue + 40) % 360);
    const ini = name ? initials(name) : null;
    if (ini) {
      const t = document.createElement('span');
      t.className = 'c-avatar__initials';
      t.setAttribute('aria-hidden', 'true'); // audit r2: SRs read "HS Han Solo"
      t.textContent = ini;
      el.append(t);
    } else {
      el.append(icon('user-circle', { size: Math.round(size * 0.55) }));
    }
  }
  if (online) {
    const dot = document.createElement('span');
    dot.className = 'c-avatar__dot';
    el.append(dot);
  }
  return el;
}

/* ---- AUDIT r2 SUPERSEDE SECTION (2026-07-03, full-surface audit ×3 agents) ----
   Later function declarations override earlier ones. Mirrors CURRENT sources:
   timestamp.js (docLocale + invalid-ts guards), message-bubble.js (ts guard +
   retry re-entry guard), typed-bubbles.js (action guards, file dispatcher,
   setFileProgress aria/glyph refresh), button.js (loading disables).
   Mac rebuild (`node scripts/build-demo-bundle.mjs`) normalizes all of this. */

function docLocale() {
  const lang = document.documentElement.lang;
  if (!lang) return undefined;
  try { Intl.getCanonicalLocales(lang); return lang; } catch { return undefined; }
}

function dayBucketLabel(ts, strings = {}, now = Date.now(), todayLabel = null) {
  const d = new Date(ts);
  if (isNaN(d)) return ''; // audit r2: invalid ts rendered literal "Invalid Date"
  const n = new Date(now);
  const locale = docLocale();
  const startOfDay = (x) => new Date(x.getFullYear(), x.getMonth(), x.getDate()).getTime();
  const dayDiff = Math.round((startOfDay(n) - startOfDay(d)) / 86400000);
  if (dayDiff <= 0) return todayLabel;
  if (dayDiff === 1) return strings.yesterday || 'Yesterday';
  if (dayDiff < 7) return d.toLocaleDateString(locale, { weekday: 'long' });
  if (d.getFullYear() === n.getFullYear()) {
    return d.toLocaleDateString(locale, { day: '2-digit', month: 'short' });
  }
  return d.toLocaleDateString(locale, { day: '2-digit', month: 'short', year: 'numeric' });
}

function formatChatTimestamp(ts, strings = {}, now = Date.now()) {
  const bucket = dayBucketLabel(ts, strings, now, null);
  if (bucket !== null) return bucket; // incl. '' for invalid ts (audit r2)
  return new Date(ts).toLocaleTimeString(docLocale(), { hour: '2-digit', minute: '2-digit' });
}

function formatTxTimestamp(ts, now = Date.now()) {
  const d = new Date(ts);
  if (isNaN(d)) return ''; // audit r2
  const locale = docLocale();
  const sameYear = d.getFullYear() === new Date(now).getFullYear();
  const date = d.toLocaleDateString(locale, sameYear
    ? { day: 'numeric', month: 'short' }
    : { day: 'numeric', month: 'short', year: 'numeric' });
  const time = d.toLocaleTimeString(locale, { hour: 'numeric', minute: '2-digit' });
  return date + ', ' + time;
}

function bubbleTime(d) {
  return d.toLocaleTimeString(docLocale(), { hour: '2-digit', minute: '2-digit' });
}

function createMessageBubble({
  direction = 'received',
  position = 'single',
  text = '',
  timestamp = null,
  status = null,
  sender = null,
  showAvatar = false,
  name = '',
  address = '',
  avatar = null,
  onRetry = null,
  strings = {},
} = {}) {
  const row = document.createElement('div');
  row.className = 'c-bubble-row';
  row.dataset.direction = direction;
  row.dataset.position = position;

  if (direction === 'received' && (showAvatar || sender !== null)) {
    const gutter = document.createElement('span');
    gutter.className = 'c-bubble-row__gutter';
    if (showAvatar && (position === 'last' || position === 'single')) {
      gutter.append(createAvatar({ src: avatar, name, address, size: 24 }));
    }
    row.append(gutter);
  }

  const el = document.createElement('div');
  el.className = 'c-bubble';

  if (sender && (position === 'first' || position === 'single')) {
    const s = document.createElement('span');
    s.className = 'c-bubble__sender';
    s.textContent = sender;
    s.style.setProperty('--sender-h', hashHue(address || name || sender));
    el.append(s);
  }

  const body = document.createElement('span');
  body.className = 'c-bubble__text';
  body.textContent = text;
  el.append(body);

  const meta = document.createElement('span');
  meta.className = 'c-bubble__meta u-tabular';
  if (timestamp != null) {
    const d = new Date(timestamp);
    if (!isNaN(d)) { // audit r2: one malformed bridge ts crashed the whole render
      const t = document.createElement('time');
      t.setAttribute('datetime', d.toISOString());
      t.textContent = bubbleTime(d);
      meta.append(t);
    }
  }
  if (direction === 'sent' && status) {
    const st = createStatusIcon(status);
    if (st) {
      st.setAttribute('width', 14);
      st.setAttribute('height', 14);
      st.removeAttribute('aria-hidden');
      st.setAttribute('role', 'img');
      st.setAttribute('aria-label', strings['status-' + status] || status);
      meta.append(st);
    }
  }
  if (meta.childNodes.length) el.append(meta);

  if (direction === 'sent' && status === 'failed') {
    row.dataset.failed = '';
    const retry = document.createElement('button');
    retry.type = 'button';
    retry.className = 'c-bubble-retry';
    retry.setAttribute('aria-label', strings.retry || 'Retry sending');
    retry.append(icon('rotate-clockwise-2', { size: 16 }));
    // audit r2: re-entry guard shared by circle + caption
    let lastRetry = 0;
    const retryGuarded = onRetry ? ((e) => {
      const t = Date.now();
      if (t - lastRetry < 500) return;
      lastRetry = t;
      onRetry(e);
    }) : null;
    if (retryGuarded) retry.addEventListener('click', retryGuarded);
    const line = document.createElement('div');
    line.className = 'c-bubble-line';
    line.append(retry, el);
    const stack = document.createElement('div');
    stack.className = 'c-bubble-stack';
    stack.append(line);
    const note = document.createElement('span');
    note.className = 'c-bubble-failnote';
    note.textContent = strings.notDelivered || 'Not delivered · Tap to retry';
    if (retryGuarded) note.addEventListener('click', retryGuarded);
    stack.append(note);
    row.append(stack);
    return row;
  }

  row.append(el);
  return row;
}

function cardTime(d) {
  return d.toLocaleTimeString(docLocale(), { hour: '2-digit', minute: '2-digit' });
}

function card(direction, title, timestamp, modifier) {
  const row = document.createElement('div');
  row.className = 'c-bubble-row';
  row.dataset.direction = direction;
  row.dataset.position = 'single';
  const el = document.createElement('div');
  el.className = 'c-tcard';
  if (modifier) el.dataset.kind = modifier;
  const head = document.createElement('div');
  head.className = 'c-tcard__head';
  const t = document.createElement('span');
  t.className = 'c-tcard__title';
  t.textContent = title;
  head.append(t);
  if (timestamp != null) {
    const d = new Date(timestamp);
    if (!isNaN(d)) { // audit r2: a malformed bridge ts must not kill the card
      const time = document.createElement('time');
      time.className = 'c-tcard__time u-tabular';
      time.setAttribute('datetime', d.toISOString());
      time.textContent = cardTime(d);
      head.append(time);
    }
  }
  el.append(head);
  row.append(el);
  return { row, el };
}

/* Action guards (audit r2): state-changing actions latch; repeatable ones
   guard rapid re-entry only. Shell contract: bridge re-render replaces cards. */
function oneShot(fn) {
  if (!fn) return undefined;
  return (e) => {
    const btn = e.currentTarget;
    if (btn.disabled || btn.dataset.acted !== undefined) return;
    btn.dataset.acted = '';
    btn.disabled = true;
    fn(e);
  };
}
function reentryGuard(fn) {
  if (!fn) return undefined;
  let last = 0;
  return (e) => {
    const now = Date.now();
    if (now - last < 500) return;
    last = now;
    fn(e);
  };
}

function createPaymentBubble({
  role = 'request-in',
  amount = '',
  fiat = '',
  status = 'actionable',
  insufficient = false,
  timestamp = null,
  onPay, onDecline, onCancel, onRetry, onDetails,
  strings = {},
} = {}) {
  const direction = (role === 'request-in' || role === 'received') ? 'received' : 'sent';
  const titles = {
    'request-in': strings.paymentRequest || 'Payment request',
    'request-out': strings.youRequested || 'You requested',
    sent: status === 'failed' ? (strings.paymentFailed || 'Payment failed') : (strings.paymentSent || 'Payment sent'),
    received: strings.paymentReceived || 'Payment received',
  };
  const { row, el } = card(direction, titles[role] || '', timestamp, 'payment'); // audit r2: unknown role rendered "undefined"
  row.dataset.status = status;

  const amountEl = document.createElement('div');
  amountEl.className = 'c-tcard__amount u-tabular';
  amountEl.dataset.tone =
    status === 'completed' ? (String(amount).startsWith('+') ? 'positive' : 'neutral')
    : (status === 'declined' || status === 'canceled' || status === 'failed') ? 'void'
    : 'pending';
  amountEl.append(document.createTextNode(amount + ' '));
  const unit = document.createElement('span');
  unit.className = 'c-tcard__unit';
  unit.textContent = 'IXI';
  amountEl.append(unit);
  el.append(amountEl);

  if (fiat) {
    const f = document.createElement('div');
    f.className = 'c-tcard__fiat u-tabular';
    if (status === 'declined' || status === 'canceled' || status === 'failed') f.dataset.tone = 'void';
    f.textContent = fiat;
    el.append(f);
  }

  const BADGES = {
    pending: ['warning', strings.pending || 'Pending', 'clock-hour-10'],
    failed: ['error', strings.failed || 'Failed', 'alert-square-rounded'],
    completed: ['success', strings.completed || 'Completed', 'check'],
    declined: ['error', strings.declined || 'Declined', 'cancel'],
    canceled: ['info', strings.canceled || 'Canceled', 'circle-x'],
  };
  if (BADGES[status]) {
    const [type, label, glyph] = BADGES[status];
    const wrap = document.createElement('div');
    wrap.className = 'c-tcard__badge';
    wrap.append(createBadge({ type, weight: 'tonal', label, icon: glyph }));
    el.append(wrap);
  }

  if (role === 'request-in' && (status === 'actionable' || status === 'processing' || status === 'failed')) {
    const decline = createButton({ label: strings.decline || 'Decline', type: 'outline', size: 32, onClick: oneShot(onDecline), disabled: status === 'processing' });
    const pay = status === 'failed'
      ? createButton({ label: strings.retry || 'Retry', type: 'fill', size: 32, icon: icon('rotate-clockwise-2', { size: 16 }), onClick: reentryGuard(onRetry) })
      : createButton({ label: strings.pay || 'Pay', type: 'fill', size: 32, icon: icon('check', { size: 16 }), onClick: oneShot(onPay), disabled: insufficient, loading: status === 'processing' });
    el.append(actionsRow(decline, pay));
    if (insufficient) {
      const note = document.createElement('div');
      note.className = 'c-tcard__note';
      note.textContent = strings.insufficient || 'Insufficient balance to pay.';
      el.append(note);
    }
  } else if (role === 'request-out' && status === 'pending') {
    el.append(actionsRow(createButton({ label: strings.cancelRequest || 'Cancel request', type: 'outline', size: 32, onClick: oneShot(onCancel) })));
  } else if (role === 'sent' && status === 'failed') {
    el.append(actionsRow(createButton({ label: strings.retry || 'Retry', type: 'fill', size: 32, icon: icon('rotate-clockwise-2', { size: 16 }), onClick: reentryGuard(onRetry) })));
  } else if (status === 'completed' || ((role === 'sent' || role === 'received') && status === 'pending')) {
    el.append(detailsLink(reentryGuard(onDetails), strings));
  }
  return row;
}

function createAppBubble({
  name = '',
  iconUrl = null,
  state = 'invite',
  direction = null,
  timestamp = null,
  onJoin, onDecline, onLaunch, onCancel, onGet, onEnd, onResume,
  strings = {},
} = {}) {
  const dir = direction || (state === 'invited' ? 'sent' : 'received');
  const title = (state === 'in-session' || state === 'ended')
    ? (strings.appSession || 'App session')
    : (strings.appInvite || 'App invite');
  const { row, el } = card(dir, title, timestamp, 'app');

  const id = document.createElement('div');
  id.className = 'c-tcard__app';
  const ic = document.createElement('span');
  ic.className = 'c-tcard__app-icon';
  if (iconUrl) {
    const img = document.createElement('img');
    img.src = iconUrl;
    img.alt = '';
    ic.append(img);
  } else {
    ic.append(icon('rocket', { size: 24 }));
  }
  const col = document.createElement('span');
  col.className = 'c-tcard__app-info';
  const nm = document.createElement('span');
  nm.className = 'c-tcard__app-name';
  nm.textContent = name;
  const sub = document.createElement('span');
  sub.className = 'c-tcard__app-sub';
  sub.textContent = {
    invite: strings.invitedYou || 'Invited you to join',
    invited: strings.youInvited || 'You have sent an invite',
    missing: strings.invitedYou || 'Invited you to join',
    'in-session': strings.inSession || 'In session',
    ended: strings.sessionEnded || 'Session ended',
  }[state] || ''; // audit r2: unknown state rendered "undefined"
  col.append(nm, sub);
  id.append(ic, col);
  el.append(id);

  if (state === 'invite') {
    el.append(actionsRow(
      createButton({ label: strings.decline || 'Decline', type: 'outline', size: 32, onClick: oneShot(onDecline) }),
      createButton({ label: strings.join || 'Join', type: 'fill', size: 32, icon: icon('check', { size: 16 }), onClick: oneShot(onJoin) }),
    ));
  } else if (state === 'invited') {
    el.append(actionsRow(
      createButton({ label: strings.cancel || 'Cancel', type: 'outline', size: 32, onClick: oneShot(onCancel) }),
      createButton({ label: strings.launchApp || 'Launch app', type: 'fill', size: 32, icon: icon('rocket', { size: 16 }), onClick: reentryGuard(onLaunch) }),
    ));
  } else if (state === 'missing') {
    el.append(actionsRow(createButton({ label: strings.getApp || 'Get app', type: 'fill', size: 32, icon: icon('download', { size: 16 }), onClick: oneShot(onGet) })));
  } else if (state === 'in-session') {
    el.append(actionsRow(
      createButton({ label: strings.endSession || 'End session', type: 'outline', size: 32, onClick: oneShot(onEnd) }),
      createButton({ label: strings.resume || 'Resume', type: 'fill', size: 32, icon: icon('player-play', { size: 16 }), onClick: reentryGuard(onResume) }),
    ));
  }
  return row;
}

function createCallBubble({
  missed = false,
  direction = 'received',
  directionLabel = '',
  duration = '',
  timestamp = null,
  onCallBack,
  strings = {},
} = {}) {
  const { row, el } = card(direction,
    missed ? (strings.missedCall || 'Missed voice call') : (strings.voiceCall || 'Voice call'),
    timestamp, 'call');
  if (missed) row.dataset.missed = '';
  const head = el.querySelector('.c-tcard__title');
  head.insertAdjacentElement('afterbegin', icon(missed ? 'phone-off' : 'phone', { size: 18 }));

  if (missed) {
    const sub = document.createElement('button');
    sub.type = 'button';
    sub.className = 'c-tcard__call-back';
    sub.textContent = strings.tapToCallBack || 'Tap to call back';
    const cb = reentryGuard(onCallBack); // repeatable — guard re-entry only
    if (cb) sub.addEventListener('click', cb);
    el.append(sub);
  } else {
    const meta = document.createElement('div');
    meta.className = 'c-tcard__call-meta u-tabular';
    meta.textContent = directionLabel + (duration ? ' · ' + duration : '');
    el.append(meta);
    const wrap = detailsLink(reentryGuard(onCallBack), { details: strings.callBack || 'Call back' });
    el.append(wrap);
  }
  return row;
}

/* file-bubble state → accessible name / leading glyph (shared with setFileProgress) */
function fileAria(state, name, strings) {
  return (state === 'offer' ? (strings.download || 'Download')
    : state === 'failed' ? (strings.retry || 'Retry')
    : state === 'progress' ? (strings.downloading || 'Downloading')
    : (strings.open || 'Open'))
    + ' ' + name;
}
function fileGlyph(state) {
  return state === 'failed' ? 'rotate-clockwise-2' : state === 'offer' ? 'download' : 'file-isr';
}

function createFileBubble({
  direction = 'received',
  name = '',
  meta = '',
  state = 'complete',
  progress = 0,
  timestamp = null,
  onAccept, onOpen, onRetry,
  strings = {},
} = {}) {
  const row = document.createElement('div');
  row.className = 'c-bubble-row';
  row.dataset.direction = direction;
  row.dataset.position = 'single';
  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-fbubble';
  el.dataset.state = state;
  // ONE persistent dispatcher keyed on live state (audit r2: progress-created
  // bubbles bound no handler — the finished download was a dead button)
  const handlers = {
    offer: oneShot(onAccept),
    failed: reentryGuard(onRetry),
    complete: reentryGuard(onOpen),
  };
  el.addEventListener('click', (e) => {
    const h = handlers[el.dataset.state];
    if (h) h(e);
  });
  if (state === 'progress') el.disabled = true;
  el.setAttribute('aria-label', fileAria(state, name, strings));

  const ic = document.createElement('span');
  ic.className = 'c-fbubble__icon';
  ic.append(icon(fileGlyph(state), { size: 20 }));
  el.append(ic);

  const col = document.createElement('span');
  col.className = 'c-fbubble__info';
  const nm = document.createElement('span');
  nm.className = 'c-fbubble__name';
  nm.textContent = name;
  const mt = document.createElement('span');
  mt.className = 'c-fbubble__meta';
  mt.textContent = state === 'failed' ? (strings.transferFailed || 'Transfer failed · Tap to retry') : meta;
  col.append(nm, mt);
  if (state === 'progress') {
    const track = document.createElement('span');
    track.className = 'c-fbubble__track';
    track.setAttribute('role', 'progressbar');
    track.setAttribute('aria-valuemin', '0');
    track.setAttribute('aria-valuemax', '100');
    track.setAttribute('aria-label', strings.downloading || 'Downloading'); // audit r2: nameless progressbar
    const p = Math.max(0, Math.min(100, Number(progress) || 0)); // NaN-safe (audit r2)
    track.setAttribute('aria-valuenow', String(p));
    const fill = document.createElement('span');
    fill.className = 'c-fbubble__fill';
    fill.style.width = p + '%';
    track.append(fill);
    col.append(track);
  }
  el.append(col);

  if (timestamp != null) {
    const d = new Date(timestamp);
    if (!isNaN(d)) { // audit r2
      const time = document.createElement('time');
      time.className = 'c-fbubble__time u-tabular';
      time.setAttribute('datetime', d.toISOString());
      time.textContent = cardTime(d);
      el.append(time);
    }
  }
  row.append(el);
  return row;
}

function setFileProgress(rowEl, progress, opts = {}) {
  const p = Math.max(0, Math.min(100, Number(progress) || 0)); // NaN-safe (audit r2)
  const fill = rowEl.querySelector('.c-fbubble__fill');
  if (fill) fill.style.width = p + '%';
  const track = rowEl.querySelector('.c-fbubble__track');
  if (track) track.setAttribute('aria-valuenow', String(p));
  const metaEl = rowEl.querySelector('.c-fbubble__meta');
  if (metaEl && opts.meta) metaEl.textContent = opts.meta;
  const bubble = rowEl.querySelector('.c-fbubble');
  const finalState = opts.state || (p >= 100 ? 'complete' : null);
  if (bubble && finalState && bubble.dataset.state !== finalState) {
    const strings = opts.strings || {};
    bubble.dataset.state = finalState;
    bubble.disabled = false;
    delete bubble.dataset.acted; // re-arm after an accept latch (audit r2)
    if (track) track.remove();
    // refresh name + glyph for the new state (audit r2: stale "Downloading" aria)
    const nm = bubble.querySelector('.c-fbubble__name');
    bubble.setAttribute('aria-label', fileAria(finalState, nm ? nm.textContent : '', strings));
    const ic = bubble.querySelector('.c-fbubble__icon');
    if (ic) { ic.textContent = ''; ic.append(icon(fileGlyph(finalState), { size: 20 })); }
    if (finalState === 'failed' && metaEl && !opts.meta) {
      metaEl.textContent = strings.transferFailed || 'Transfer failed · Tap to retry';
    }
  }
}

function createButton({
  label,
  type = 'fill',
  size = 44,
  intent = 'default',
  width = 'hug',
  icon = null,
  iconPosition = 'leading',
  ariaLabel,
  loading = false,
  disabled = false,
  onClick,
} = {}) {
  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-button';
  el.dataset.type = type;
  el.dataset.size = String(size);
  el.dataset.intent = intent;
  el.dataset.width = width;

  const hasLabel = label != null && label !== '';
  if (!hasLabel) {
    el.dataset.iconOnly = '';
    if (ariaLabel) el.setAttribute('aria-label', ariaLabel);
    else console.warn('c-button: icon-only button requires ariaLabel');
  }

  if (icon) icon.classList.add('c-button__icon');
  if (icon && iconPosition === 'leading') el.append(icon);

  if (hasLabel) {
    const text = document.createElement('span');
    text.className = 'c-button__label';
    text.textContent = label;
    el.append(text);
  }

  if (icon && iconPosition === 'trailing') el.append(icon);

  if (onClick) el.addEventListener('click', onClick);

  // disabled BEFORE setLoading — loading remembers/restores the caller's state
  el.disabled = disabled;
  setLoading(el, loading);
  return el;
}

function setLoading(el, loading) {
  morphWidth(el, () => {
    const existing = el.querySelector('.c-button__spinner');
    if (loading) {
      if (!existing) {
        const spinner = document.createElement('span');
        spinner.className = 'c-button__spinner';
        spinner.setAttribute('aria-hidden', 'true');
        el.prepend(spinner);
      }
      el.dataset.loading = '';
      el.setAttribute('aria-busy', 'true');
      // audit r2: loading ≠ inert — keyboard activation still fired onClick
      if (!el.disabled) { el.dataset.loadingDisabled = ''; el.disabled = true; }
    } else {
      existing?.remove();
      delete el.dataset.loading;
      el.removeAttribute('aria-busy');
      if (el.dataset.loadingDisabled !== undefined) {
        delete el.dataset.loadingDisabled;
        el.disabled = false;
      }
    }
  });
}
/* ---- end AUDIT r2 SUPERSEDE SECTION ---- */

  window.Spixi = { formatChatTimestamp: formatChatTimestamp, formatTxTimestamp: formatTxTimestamp, startTimestampTicker: startTimestampTicker, createAvatar: createAvatar, formatCount: formatCount, createStatusIcon: createStatusIcon, createIndicator: createIndicator, createIndicators: createIndicators, createExcerpt: createExcerpt, createChatItem: createChatItem, refreshTimestamps: refreshTimestamps, createButton: createButton, setLoading: setLoading, setSuccess: setSuccess, createTopbar: createTopbar, setTopbarSub: setTopbarSub, createBottomNav: createBottomNav, setNavActive: setNavActive, setNavBadge: setNavBadge, createChip: createChip, setChipSelected: setChipSelected, createSearchField: createSearchField, setSearchValue: setSearchValue, getSearchValue: getSearchValue, clearHighlights: clearHighlights, setHighlights: setHighlights, createBadge: createBadge, createTxItem: createTxItem, overlayId: overlayId, setOverlayOpts: setOverlayOpts, openOverlay: openOverlay, dismissOverlay: dismissOverlay, dismissTopOverlay: dismissTopOverlay, createSheet: createSheet, openSheet: openSheet, closeSheet: closeSheet, createModal: createModal, openModal: openModal, closeModal: closeModal, createWarningBanner: createWarningBanner, setWarning: setWarning, showToast: showToast, showCallBar: showCallBar, hideCallBar: hideCallBar, hashHue: hashHue, dayBucketLabel: dayBucketLabel, createMessageBubble: createMessageBubble, createDateSeparator: createDateSeparator, createComposer: createComposer, clearComposer: clearComposer, createPaymentBubble: createPaymentBubble, createAppBubble: createAppBubble, createCallBubble: createCallBubble, createFileBubble: createFileBubble, setFileProgress: setFileProgress, createUnreadDivider: createUnreadDivider };
})();
