/* GENERATED by scripts/build-demo-bundle.mjs — DO NOT EDIT.
 * Real component sources bundled for file:// demos. Requires icons.iife.js first.
 */
(function () {
  var icon = window.SpixiIcons.icon;

/* ---- src/components/timestamp.js ---- */
function formatChatTimestamp(ts, now = Date.now(), strings = {}) {
  const d = new Date(ts);
  const n = new Date(now);
  const locale = document.documentElement.lang || undefined;
  const startOfDay = (x) => new Date(x.getFullYear(), x.getMonth(), x.getDate()).getTime();
  const dayDiff = Math.round((startOfDay(n) - startOfDay(d)) / 86400000);
  if (dayDiff <= 0) {
    return d.toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit', hour12: false });
  }
  if (dayDiff === 1) return strings.yesterday || 'Yesterday';
  if (dayDiff < 7) return d.toLocaleDateString(locale, { weekday: 'long' });
  if (d.getFullYear() === n.getFullYear()) {
    return d.toLocaleDateString(locale, { day: '2-digit', month: 'short' });
  }
  return d.toLocaleDateString(locale, { day: '2-digit', month: 'short', year: 'numeric' });
}
function startTimestampTicker(cb) {
  let minuteTimer = setInterval(() => { if (!document.hidden) cb(); }, 60000);
  const scheduleMidnight = () => {
    const now = new Date();
    const next = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 0, 0, 1);
    return setTimeout(() => { cb(); midnightTimer = scheduleMidnight(); }, next - now);
  };
  let midnightTimer = scheduleMidnight();
  return () => { clearInterval(minuteTimer); clearTimeout(midnightTimer); };
}

/* ---- src/components/avatar.js ---- */
function hashHue(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  return h % 360;
}
function initials(name) {
  const parts = name.trim().split(/\s+/).slice(0, 2);
  const chars = parts.map(p => p[0].toUpperCase()).join('');
  return /^[A-Za-z]/.test(name) ? chars : null;
}
function createAvatar({ src = null, name = '', address = '', size = 48, online = false } = {}) {
  const el = document.createElement('span');
  el.className = 'c-avatar';
  el.style.width = size + 'px';
  el.style.height = size + 'px';
  if (src) {
    const img = document.createElement('img');
    img.className = 'c-avatar__img';
    img.src = src;
    img.alt = '';
    el.append(img);
  } else {
    const hue = hashHue(address || name);
    el.style.backgroundImage =
      'linear-gradient(135deg, hsl(' + hue + ', 62%, 62%), hsl(' + ((hue + 40) % 360) + ', 58%, 45%))';
    const ini = name ? initials(name) : null;
    if (ini) {
      const t = document.createElement('span');
      t.className = 'c-avatar__initials';
      t.textContent = ini;
      t.style.fontSize = Math.round(size * 0.38) + 'px';
      el.append(t);
    } else {
      el.append(icon('user-circle', { size: Math.round(size * 0.55) }));
    }
  }
  if (online) {
    const dot = document.createElement('span');
    dot.className = 'c-avatar__dot';
    el.append(dot);
  }
  return el;
}

/* ---- src/components/chatlist-item.js ---- */
const STATUS = {
  sending: { glyph: 'clock-hour-10', tone: 'neutral' },
  sent: { glyph: 'check', tone: 'neutral' },
  delivered: { glyph: 'checks', tone: 'neutral' },
  read: { glyph: 'checks', tone: 'read' },
  failed: { glyph: 'alert-small', tone: 'failed' },
};
function createStatusIcon(status) {
  const s = STATUS[status];
  if (!s) return null;
  const el = icon(s.glyph, { size: 16 });
  el.classList.add('c-status-icon');
  el.dataset.tone = s.tone;
  return el;
}
function createIndicator({ count = 0, mention = false, muted = false } = {}) {
  const el = document.createElement('span');
  el.className = 'c-indicator';
  if (mention) {
    el.dataset.variant = 'mention';
    el.textContent = '@';
  } else if (count > 0) {
    el.dataset.variant = muted ? 'count-muted' : 'count';
    el.textContent = count > 99 ? '99+' : String(count);
  } else if (muted) {
    el.dataset.variant = 'muted';
    el.append(icon('bell-off', { size: 12 }));
  } else return null;
  return el;
}
const EXCERPT_GLYPHS = {
  file: 'file-isr', gif: 'gif', call: 'phone', 'call-missed': 'phone-off',
  payment: 'wallet', 'app-invite': 'apps', draft: 'pencil',
};
function createExcerpt({ type = 'text', text = '', sender = null } = {}) {
  const el = document.createElement('span');
  el.className = 'c-excerpt';
  el.dataset.type = type;
  const glyph = EXCERPT_GLYPHS[type];
  if (glyph) el.append(icon(glyph, { size: 16 }));
  if (sender) {
    const s = document.createElement('span');
    s.className = 'c-excerpt__sender';
    s.textContent = sender + ': ';
    el.append(s);
  }
  const t = document.createElement('span');
  t.className = 'c-excerpt__text';
  if (type === 'draft') {
    const prefix = document.createElement('span');
    prefix.className = 'c-excerpt__draft';
    prefix.textContent = 'Draft: ';
    t.append(prefix);
    t.append(document.createTextNode(text));
  } else if (type === 'mention' && text.includes('@')) {
    const i = text.indexOf('@');
    const end = text.indexOf(' ', i);
    const stop = end === -1 ? text.length : end;
    t.append(document.createTextNode(text.slice(0, i)));
    const m = document.createElement('span');
    m.className = 'c-excerpt__mention';
    m.textContent = text.slice(i, stop);
    t.append(m, document.createTextNode(text.slice(stop)));
  } else {
    t.textContent = text;
  }
  el.append(t);
  return el;
}
function createChatItem({
  name, address = '', avatar = null, online = false,
  timestamp, status = null, pinned = false,
  unread = 0, mention = false, muted = false,
  excerpt = { type: 'text', text: '' },
  selected = false, onClick,
} = {}) {
  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-chatlist-item';
  if (unread > 0 || mention) el.dataset.unread = '';
  if (selected) el.setAttribute('aria-current', 'true');
  el.append(createAvatar({ src: avatar, name, address, size: 48, online }));
  const content = document.createElement('span');
  content.className = 'c-chatlist-item__content';
  const nameEl = document.createElement('span');
  nameEl.className = 'c-chatlist-item__name';
  nameEl.textContent = name || address;
  content.append(nameEl, createExcerpt(excerpt));
  el.append(content);
  const right = document.createElement('span');
  right.className = 'c-chatlist-item__right';
  const row1 = document.createElement('span');
  row1.className = 'c-chatlist-item__meta';
  const statusEl = createStatusIcon(status);
  if (statusEl) row1.append(statusEl);
  if (pinned) row1.append(icon('pin', { size: 16 }));
  if (timestamp != null) {
    const time = document.createElement('span');
    time.className = 'c-chatlist-item__time u-tabular';
    time.textContent = formatChatTimestamp(timestamp);
    time.dataset.ts = timestamp;
    row1.append(time);
  }
  right.append(row1);
  const ind = createIndicator({ count: unread, mention, muted });
  if (ind) {
    const row2 = document.createElement('span');
    row2.className = 'c-chatlist-item__indicators';
    row2.append(ind);
    right.append(row2);
  }
  el.append(right);
  if (onClick) el.addEventListener('click', onClick);
  return el;
}
function refreshTimestamps(rootEl) {
  for (const t of rootEl.querySelectorAll('.c-chatlist-item__time[data-ts]')) {
    t.textContent = formatChatTimestamp(Number(t.dataset.ts));
  }
}

/* ---- src/components/button.js ---- */
function morphWidth(el, mutate) {
  if (el.dataset.width === 'full' || !el.isConnected) { mutate(); return; }
  const w0 = el.offsetWidth;
  mutate();
  el.style.width = 'auto';
  const w1 = el.offsetWidth;
  el.style.width = w0 + 'px';
  void el.offsetWidth;
  el.style.width = w1 + 'px';
  clearTimeout(el._morphTimer);
  el._morphTimer = setTimeout(() => { el.style.width = ''; }, 250);
}
function createButton({
  label, type = 'fill', size = 44, intent = 'default', width = 'hug',
  icon: iconEl = null, iconPosition = 'leading', ariaLabel,
  loading = false, disabled = false, onClick,
} = {}) {
  const el = document.createElement('button');
  el.type = 'button';
  el.className = 'c-button';
  el.dataset.type = type;
  el.dataset.size = String(size);
  el.dataset.intent = intent;
  el.dataset.width = width;
  const hasLabel = label != null && label !== '';
  if (!hasLabel) {
    el.dataset.iconOnly = '';
    if (ariaLabel) el.setAttribute('aria-label', ariaLabel);
    else console.warn('c-button: icon-only button requires ariaLabel');
  }
  if (iconEl) iconEl.classList.add('c-button__icon');
  if (iconEl && iconPosition === 'leading') el.append(iconEl);
  if (hasLabel) {
    const text = document.createElement('span');
    text.className = 'c-button__label';
    text.textContent = label;
    el.append(text);
  }
  if (iconEl && iconPosition === 'trailing') el.append(iconEl);
  if (onClick) el.addEventListener('click', onClick);
  setLoading(el, loading);
  el.disabled = disabled;
  return el;
}
function setLoading(el, loading) {
  morphWidth(el, () => {
    const existing = el.querySelector('.c-button__spinner');
    if (loading) {
      if (!existing) {
        const spinner = document.createElement('span');
        spinner.className = 'c-button__spinner';
        spinner.setAttribute('aria-hidden', 'true');
        el.prepend(spinner);
      }
      el.dataset.loading = '';
      el.setAttribute('aria-busy', 'true');
    } else {
      if (existing) existing.remove();
      delete el.dataset.loading;
      el.removeAttribute('aria-busy');
    }
  });
}
const CHECK_PATH = 'M5 12l5 5L20 7';
function setSuccess(el, { label = null, duration = 1400 } = {}) {
  if (el.dataset.success !== undefined) return;
  const original = [...el.childNodes].filter(n => !(n.classList && n.classList.contains('c-button__spinner')));
  const originalDisabled = el.disabled;
  morphWidth(el, () => {
    el.textContent = '';
    el.dataset.success = '';
    el.disabled = true;
    delete el.dataset.loading;
    el.removeAttribute('aria-busy');
    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttribute('viewBox', '0 0 24 24');
    svg.setAttribute('fill', 'none');
    svg.setAttribute('aria-hidden', 'true');
    svg.classList.add('c-button__icon');
    const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    path.setAttribute('d', CHECK_PATH);
    path.setAttribute('stroke', 'currentColor');
    path.setAttribute('stroke-width', '2.5');
    path.setAttribute('stroke-linecap', 'round');
    path.setAttribute('stroke-linejoin', 'round');
    svg.append(path);
    el.append(svg);
    const text = document.createElement('span');
    text.className = 'c-button__label';
    text.setAttribute('role', 'status');
    if (label) text.textContent = label;
    el.append(text);
  });
  setTimeout(() => {
    morphWidth(el, () => {
      el.textContent = '';
      el.append(...original);
      delete el.dataset.success;
      el.disabled = originalDisabled;
    });
  }, duration);
}

/* ---- src/components/topbar.js ---- */
function createTopbar({ variant = 'view', title = '', logo = null, onBack, actions = [] } = {}) {
  const el = document.createElement('header');
  el.className = 'c-topbar';
  el.dataset.variant = variant;
  if (variant === 'view' && onBack) {
    el.append(createButton({
      type: 'text', size: 44,
      icon: icon('arrow-left'),
      ariaLabel: 'Back',
      onClick: onBack,
    }));
  }
  const titleEl = document.createElement('div');
  titleEl.className = 'c-topbar__title';
  if (variant === 'root' && logo) {
    const mark = icon('logo', { size: 28 });
    mark.classList.add('c-topbar__logo');
    const word = document.createElement('span');
    word.textContent = title || 'Spixi';
    titleEl.append(mark, word);
  } else {
    titleEl.textContent = title;
  }
  el.append(titleEl);
  if (actions.length) {
    const wrap = document.createElement('div');
    wrap.className = 'c-topbar__actions';
    for (const a of actions) {
      wrap.append(createButton({
        type: 'text', size: 44,
        icon: icon(a.icon),
        ariaLabel: a.label,
        onClick: a.onClick,
      }));
    }
    el.append(wrap);
  }
  return el;
}

/* ---- src/components/bottomnav.js ---- */
function createBottomNav({ items = [], active, onChange } = {}) {
  const el = document.createElement('nav');
  el.className = 'c-bottomnav';
  el.setAttribute('aria-label', 'Main');
  const buttons = new Map();
  for (const item of items) {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'c-bottomnav__item';
    btn.dataset.id = item.id;
    const iconwrap = document.createElement('span');
    iconwrap.className = 'c-bottomnav__iconwrap';
    if (item.avatar) {
      const img = document.createElement('img');
      img.className = 'c-bottomnav__avatar';
      img.src = item.avatar;
      img.alt = '';
      iconwrap.append(img);
    } else {
      iconwrap.append(icon(item.icon));
    }
    const badge = document.createElement('span');
    badge.className = 'c-bottomnav__badge';
    badge.hidden = true;
    iconwrap.append(badge);
    const label = document.createElement('span');
    label.className = 'c-bottomnav__label';
    label.textContent = item.label;
    btn.append(iconwrap, label);
    btn.addEventListener('click', () => {
      setActive(item.id);
      if (onChange) onChange(item.id);
    });
    el.append(btn);
    buttons.set(item.id, btn);
    if (item.badge) setBadge(item.id, item.badge);
  }
  function setActive(id) {
    for (const [itemId, btn] of buttons) {
      if (itemId === id) btn.setAttribute('aria-current', 'page');
      else btn.removeAttribute('aria-current');
    }
  }
  function setBadge(id, count) {
    const btn = buttons.get(id);
    if (!btn) return;
    const badge = btn.querySelector('.c-bottomnav__badge');
    if (count > 0) {
      badge.textContent = count > 99 ? '99+' : String(count);
      badge.hidden = false;
    } else badge.hidden = true;
  }
  if (active) setActive(active);
  el.setActive = setActive;
  el.setBadge = setBadge;
  return el;
}

  window.Spixi = { formatChatTimestamp: formatChatTimestamp, startTimestampTicker: startTimestampTicker, createAvatar: createAvatar, createStatusIcon: createStatusIcon, createIndicator: createIndicator, createExcerpt: createExcerpt, createChatItem: createChatItem, refreshTimestamps: refreshTimestamps, createButton: createButton, setLoading: setLoading, setSuccess: setSuccess, createTopbar: createTopbar, createBottomNav: createBottomNav };
})();
