/* Build per-language dictionaries (i18n batch — starter translations).
 *
 * For each target locale:
 *   1) REUSE the shipped legacy translation (Resources/Raw/lang/<code>.txt) for
 *      any key whose English matches a legacy id AND is placeholder-free (so a
 *      legacy {0}/{1} string can never land under a {n}/{q}/{date} key).
 *   2) Otherwise take the Claude-drafted value from src/strings/draft/<code>.json.
 *   3) Fall back to English (logged) so a locale is never missing a key.
 * Emits src/strings/<code>.json + <code>.js. With --todo, writes the per-locale
 * lists of keys still needing a draft translation (fed to the translators).
 *
 *   node scripts/build-locales.mjs [--todo]
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const TODO = process.argv.includes('--todo');
const LANGS = ['de-de', 'es-co', 'fr-fr', 'sr-sp', 'sl-si', 'ru-ru', 'pt-br'];
const enUS = JSON.parse(readFileSync(join(root, 'src/strings/en-us.json'), 'utf8'));
const KEYS = Object.keys(enUS);
const PH = /\{[^}]+\}/;

function norm(s) {
  return s.toLowerCase().replace(/\{[^}]*\}/g, '').replace(/[’']/g, "'").replace(/[^a-z0-9]+/g, ' ').trim();
}
function parseLang(code) {
  const p = join(root, 'Spixi/Resources/Raw/lang', code + '.txt');
  const m = new Map();
  if (!existsSync(p)) return m;
  for (const raw of readFileSync(p, 'utf8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith(';')) continue;
    const eq = line.indexOf('='); if (eq < 0) continue;
    const id = line.slice(0, eq).trim(); const val = line.slice(eq + 1).trim();
    if (id && id !== 'language-code' && id !== 'language') m.set(id, val);
  }
  return m;
}
// English value -> legacy id (placeholder-free only, so reuse is placeholder-safe)
const enLegacy = parseLang('en-us');
const valToId = new Map();
for (const [id, val] of enLegacy) { if (PH.test(val)) continue; const n = norm(val); if (n && !valToId.has(n)) valToId.set(n, id); }
// my key -> legacy id (placeholder-free English on my side too)
const keyToId = {};
for (const k of KEYS) { if (PH.test(enUS[k])) continue; const id = valToId.get(norm(enUS[k])); if (id) keyToId[k] = id; }

let draft = {};
const draftDir = join(root, 'src/strings/draft');

for (const code of LANGS) {
  const legacy = parseLang(code);
  const draftFile = join(draftDir, code + '.json');
  const drafted = existsSync(draftFile) ? JSON.parse(readFileSync(draftFile, 'utf8')) : {};
  const out = {}, todo = {}, stats = { reused: 0, drafted: 0, english: 0 };
  for (const k of KEYS) {
    const id = keyToId[k];
    const leg = id ? legacy.get(id) : null;
    if (leg && leg.trim()) { out[k] = leg; stats.reused++; continue; }
    if (drafted[k] && drafted[k].trim()) { out[k] = drafted[k]; stats.drafted++; continue; }
    out[k] = enUS[k]; stats.english++; todo[k] = enUS[k];         // needs a draft
  }
  if (TODO) { mkdirSync(draftDir, { recursive: true }); writeFileSync(join(draftDir, code + '.todo.json'), JSON.stringify(todo, null, 2) + '\n'); }
  else {
    mkdirSync(join(root, 'src/strings'), { recursive: true });
    writeFileSync(join(root, 'src/strings', code + '.json'), JSON.stringify(out, null, 2) + '\n');
    const body = KEYS.map((k) => `  ${/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)}: ${JSON.stringify(out[k])},`).join('\n');
    writeFileSync(join(root, 'src/strings', code + '.js'), `/* GENERATED by scripts/build-locales.mjs — starter translation, review before ship. */\nexport const ${code.replace('-', '')} = {\n${body}\n};\nexport default ${code.replace('-', '')};\n`);
  }
  console.log(`${code}: reuse ${stats.reused} · draft ${stats.drafted} · english-fallback ${stats.english}` + (TODO ? ` → ${Object.keys(todo).length} to translate` : ''));
}
