/**
 * Regenerates src/components/icons.js (ESM) and src/components/icons.iife.js
 * (classic script for file:// demos) from src/assets/icons/tabler-icon-*.svg.
 *
 * Pipeline (DECISIONS.md #32): Figma icons frame → bulk SVG export by Damir →
 * this script. Ink fills/strokes (#131415) become currentColor; brand fills/
 * strokes (#3050BD) become var(--icon-accent, #3050bd) so they theme.
 * logo.svg IS processed into the registry (DECISIONS #32/#36) — all its inks
 * (including brand #3050BD) become currentColor so it inherits its context
 * color (topbar title ink — works in both modes).
 *
 * Run: node scripts/generate-icons.mjs   (from repo root)
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = join(root, 'src/assets/icons');
const OUT_ESM = join(root, 'src/components/icons.js');
const OUT_IIFE = join(root, 'src/components/icons.iife.js');

const entries = {};
for (const file of readdirSync(ASSETS).sort()) {
  if (!file.endsWith('.svg')) continue;
  const isLogo = file === 'logo.svg';
  if (!isLogo && !file.startsWith('tabler-icon-')) continue;
  const name = isLogo ? 'logo' : file.replace('tabler-icon-', '').replace('.svg', '');
  const svg = readFileSync(join(ASSETS, file), 'utf8');
  const viewBox = (svg.match(/viewBox="([^"]+)"/) || [])[1];
  if (!viewBox) console.warn(`icons: ${file} has no viewBox — defaulting to "0 0 24 24" (a non-24 grid export would clip)`);
  let inner = svg
    .replace(/<\/?svg[^>]*>/g, '')
    // attribute-per-line exports: join with a space (NOT ''), then collapse
    // inter-tag whitespace for size
    .replace(/\s*\n\s*/g, ' ')
    .replace(/>\s+</g, '><')
    .trim();
  // raw Tabler downloads carry an invisible background stub — dead bytes
  inner = inner.replace(/<path\b[^>]*\bd="M0 0h24v24H0z"[^>]*\/?>(?:\s*<\/path>)?/g, '');
  // theme ink + brand colors (fills AND strokes)
  inner = inner
    .replace(/fill="#131415"/gi, 'fill="currentColor"')
    .replace(/stroke="#131415"/gi, 'stroke="currentColor"');
  // logo inherits its context color (topbar title ink — works in both modes);
  // other brand-colored glyphs keep themed accent
  inner = isLogo
    ? inner
        .replace(/fill="#3050BD"/gi, 'fill="currentColor"')
        .replace(/stroke="#3050BD"/gi, 'stroke="currentColor"')
    : inner
        .replace(/fill="#3050BD"/gi, 'fill="var(--icon-accent, #3050bd)"')
        .replace(/stroke="#3050BD"/gi, 'stroke="var(--icon-accent, #3050bd)"');
  // raw Tabler downloads carry fill="currentColor" on the ROOT <svg> (stripped
  // above) with bare inner shapes — the factory root uses fill="none", so bare
  // shapes went invisible (DECISIONS #40). Give any fill-less shape an explicit
  // currentColor. <g> wrappers are left alone: their fill-less children are
  // covered here, and hex fills on <g> were themed by the replaces above.
  inner = inner.replace(
    /<(path|circle|rect|ellipse|polygon|polyline|line)\b(?![^>]*\bfill=)/g,
    '<$1 fill="currentColor"'
  );
  // loud warnings for anything the pipeline can't theme
  for (const m of inner.matchAll(/style="[^"]*"/g)) {
    if (/(?:fill|stroke)\s*:/.test(m[0])) {
      console.warn(`icons: ${file} has inline ${m[0]} — style attributes are not themed, clean up the export manually`);
    }
  }
  for (const m of inner.matchAll(/(fill|stroke)="(#[0-9a-fA-F]{6})"/g)) {
    const hex = m[2].toLowerCase();
    if (hex !== '#131415' && hex !== '#3050bd') {
      console.warn(`icons: ${file} ships hardcoded ${m[1]}="${m[2]}" — not a known ink/brand color, will be wrong in dark mode`);
    }
  }
  entries[name] = { v: viewBox || '0 0 24 24', b: inner };
}

const registry = JSON.stringify(entries, null, 0)
  .replace(/","/g, '",\n  "')
  .replace('{"', '{\n  "')
  .replace('"}', '"\n}');

const factory = `
/** Create an inline SVG icon element (filled Tabler set + logo from Figma). */
function iconFactory(ICONS) {
  return function icon(name, opts) {
    opts = opts || {};
    const entry = ICONS[name];
    if (!entry) console.warn('icons: unknown icon "' + name + '"');
    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttribute('viewBox', entry ? entry.v : '0 0 24 24');
    svg.setAttribute('width', opts.size || 24);
    svg.setAttribute('height', opts.size || 24);
    svg.setAttribute('fill', 'none');
    if (opts.label) { svg.setAttribute('role', 'img'); svg.setAttribute('aria-label', opts.label); }
    else svg.setAttribute('aria-hidden', 'true');
    svg.innerHTML = entry ? entry.b : ''; // static registry strings only — never user data
    return svg;
  };
}`;

const header = (kind) => `/* GENERATED by scripts/generate-icons.mjs from src/assets/icons/ (${Object.keys(entries).length} icons)
 * DO NOT EDIT — re-export from Figma + re-run the script instead. ${kind}
 */`;

writeFileSync(OUT_ESM, `${header('ESM module.')}
export const ICONS = ${registry};
${factory}
export const icon = iconFactory(ICONS);
`);

writeFileSync(OUT_IIFE, `${header('Classic script for file:// demos — exposes window.SpixiIcons.')}
(function () {
  var ICONS = ${registry};
  ${factory}
  window.SpixiIcons = { ICONS: ICONS, icon: iconFactory(ICONS) };
})();
`);

/* ★ Session H review (auditor C, MAJOR-2 belt): READ BOTH FILES BACK and require the
 * registry to appear byte-identically in each. The two writes come from one string, so
 * they can only drift when a write LANDS PARTIALLY or one file was stale at commit time
 * — Session G shipped exactly that (external-link in icons.js, absent from icons.iife.js,
 * so the #710 pin was red in every clean clone). Fail loud here; the suite carries the
 * structural equality gate as the second belt. */
{
  const backEsm = readFileSync(OUT_ESM, 'utf8');
  const backIife = readFileSync(OUT_IIFE, 'utf8');
  if (!backEsm.includes(registry) || !backIife.includes(registry)) {
    console.error('generate-icons: READ-BACK FAILED — a written registry does not match the generated string (IO/mount corruption class, #175). Re-run from a local terminal.');
    process.exit(1);
  }
}
console.log('generated', Object.keys(entries).length, 'icons →', OUT_ESM, '+', OUT_IIFE, '· read-back \u2713');
