/**
 * Regenerates src/components/icons.js (ESM) and src/components/icons.iife.js
 * (classic script for file:// demos) from src/assets/icons/tabler-icon-*.svg.
 *
 * Pipeline (DECISIONS.md #32): Figma icons frame → bulk SVG export by Damir →
 * this script. Ink fills (#131415) become currentColor; brand fills (#3050BD)
 * become var(--icon-accent, #3050bd) so they theme. logo.svg is NOT processed —
 * it keeps brand colors and is referenced as an <img>/inline asset directly.
 *
 * Run: node scripts/generate-icons.mjs   (from repo root)
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = join(root, 'src/assets/icons');
const OUT_ESM = join(root, 'src/components/icons.js');
const OUT_IIFE = join(root, 'src/components/icons.iife.js');

const entries = {};
for (const file of readdirSync(ASSETS).sort()) {
  if (!file.endsWith('.svg')) continue;
  const isLogo = file === 'logo.svg';
  if (!isLogo && !file.startsWith('tabler-icon-')) continue;
  const name = isLogo ? 'logo' : file.replace('tabler-icon-', '').replace('.svg', '');
  const svg = readFileSync(join(ASSETS, file), 'utf8');
  const viewBox = (svg.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 24 24';
  let inner = svg
    .replace(/<\/?svg[^>]*>/g, '')
    .replace(/\s*\n\s*/g, '')
    .replace(/fill="#131415"/gi, 'fill="currentColor"')
    .trim();
  // logo inherits its context color (topbar title ink — works in both modes);
  // other brand-colored glyphs keep themed accent
  inner = isLogo
    ? inner.replace(/fill="#3050BD"/gi, 'fill="currentColor"')
    : inner.replace(/fill="#3050BD"/gi, 'fill="var(--icon-accent, #3050bd)"');
  entries[name] = { v: viewBox, b: inner };
}

const registry = JSON.stringify(entries, null, 0)
  .replace(/","/g, '",\n  "')
  .replace('{"', '{\n  "')
  .replace('"}', '"\n}');

const factory = `
/** Create an inline SVG icon element (filled Tabler set + logo from Figma). */
function iconFactory(ICONS) {
  return function icon(name, opts) {
    opts = opts || {};
    const entry = ICONS[name];
    if (!entry) console.warn('icons: unknown icon "' + name + '"');
    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttribute('viewBox', entry ? entry.v : '0 0 24 24');
    svg.setAttribute('width', opts.size || 24);
    svg.setAttribute('height', opts.size || 24);
    svg.setAttribute('fill', 'none');
    if (opts.label) { svg.setAttribute('role', 'img'); svg.setAttribute('aria-label', opts.label); }
    else svg.setAttribute('aria-hidden', 'true');
    svg.innerHTML = entry ? entry.b : ''; // static registry strings only — never user data
    return svg;
  };
}`;

const header = (kind) => `/* GENERATED by scripts/generate-icons.mjs from src/assets/icons/ (${Object.keys(entries).length} icons)
 * DO NOT EDIT — re-export from Figma + re-run the script instead. ${kind}
 */`;

writeFileSync(OUT_ESM, `${header('ESM module.')}
export const ICONS = ${registry};
${factory}
export const icon = iconFactory(ICONS);
export const ICON_NAMES = Object.keys(ICONS);
`);

writeFileSync(OUT_IIFE, `${header('Classic script for file:// demos — exposes window.SpixiIcons.')}
(function () {
  var ICONS = ${registry};
  ${factory}
  window.SpixiIcons = { ICONS: ICONS, icon: iconFactory(ICONS), ICON_NAMES: Object.keys(ICONS) };
})();
`);

console.log('generated', Object.keys(entries).length, 'icons →', OUT_ESM, '+', OUT_IIFE);
